### ISSUE TITLE
CPU usage issue related to uninstalled games in the Library

### ISSUE THREAD

**Issue by Zerathos** [DirtDiglett/Pressure-for-Steam#100]
If the currently selected game in the Library is not currently installed, CPU usage will spike. I can literally [watch my CPU temp go up and down and select different games](http://i.imgur.com/aSas1tM.png). The great big long peak at the start is from leaving it sitting on one, which was when I noticed my fan going like crazy, then I started checked which process was causing the problem and immediately remembered this bug from Metro. Clicked around on some other games and you can see the temperature graph move around. The game in particular I noticed it on is Paper Monsters Recut.

**Comment by Asphira** [comment]
This will be now fixed in the newest update being pushed shortly.

It was due to the welcome information for uninstalled games not showing.
