### ISSUE TITLE
Workshop downloads aren't styled

### ISSUE THREAD

**Issue by Iwasawafag** [DirtDiglett/Pressure-for-Steam#115]
![](http://i.imgur.com/8XHiCzx.png)

**Comment by DirtDiglett** [comment]
Hey @Asphira, fix this while you're re-doing the download page like you promised :laughing:

**Comment by FlaminSarge** [comment]
The relevant file is ugcdownloadpanel.layout, right? What other files are relevant for downloadsummarypanel.layout (which I assume is what styles these)?

**Comment by DirtDiglett** [comment]
@FlaminSarge There are a few files in use for the downloads page:
`appdownloadpanel.layout` -> Individual game sections in the downloads page.
`downloadspage.layout` -> General container for everything.
`downloadsummarypanel.layout` > This is the top area with the bars and stats.
`ugcdownloadpanel.layout` -> Appears to be for the workshop "**U**pdate **G**ame **C**ontent **Download Panel**"
