### ISSUE TITLE
More Alignment stuff and one bug

### ISSUE THREAD

**Issue by Holly-Chan** [DirtDiglett/Pressure-for-Steam#118]
Hey Diglet ! 
Remember #91 in the Misaligned section?
There are 3 things that still needs fixing:

![b](https://cloud.githubusercontent.com/assets/9482398/5154481/871f1b9e-7247-11e4-8b0a-a9d87951a0d8.jpg)
**1°** The "Downloading" word needs to be lowered by 1 px
 
**2°** "View News" icon needs to be raised by 1px too.(ignore the marking on the "auto updates enabled",that one is aligned)

**3°**  I marked a bug that didnt happen in previous versions of the skin : See how the top left of the letter "B" in the "Batman" word is a little..transparent...or greyed out? This is happening with the current version without the "fixes" that i did.

Here is my "fixed" version.
![fix](https://cloud.githubusercontent.com/assets/9482398/5154494/485e225a-7248-11e4-9843-cbfbe7b25d76.jpg)
And here is what i changed :
**resource > layout > appdownloadpanel > search for "update type label" > set margin-top = 46 > search for "graphics/news" > set = y0+1**

Another thing that i think is misaligned is the Install icon in the game's grid page...the icon and the word are too close to each other:
![b2](https://cloud.githubusercontent.com/assets/9482398/5154513/339e6018-7249-11e4-8c72-357784d3cfc2.jpg)

Here is my "fixed" version:
![fix1](https://cloud.githubusercontent.com/assets/9482398/5154515/42ec1c72-7249-11e4-86db-cf109b4d6685.png)

And here is what i changed:

**resource > layout > gamespagegridchrome > search for "install_icon" > set padding left and righ to 11 and x0+9 twice.**

I dont know if what i changed is actually a fix because i might have done something more or  less than necessary. but it worked for me :stuck_out_tongue: 

**ANOTHER THING I LIKE TO ASK**
Why the scrolling on the game's grid page is not as smooth compared to the default skin? is the skin THAT demanding to even lag my fx6300 + R9 270X? hehehe

**TEACH ME SENPAI SECTION**
If its not too much trouble for you...could you teach me how to change a few things? Im asking for you to teach me because i completely understand WHY you made those changes...mostly to adapt the skin to different languages and peoples.The thing is is that those things that made you change didnt affect me so i would like to revert back to them as i did find them better looking.  And i completely understand if you dont want to tell me how but i have to give it a shot so here it goes : 

How can i make the play button the same width as the install and the details button in the grid's page(assuming that the details and the install are the same width)?

In the original mockup... the header words were black and that i know how to change...but there was something more... the words on the header had an effect that looked like the words had "depth"  as you can see in this link(its the same that is on the skin's community page:

http://i.imgur.com/cgsZMul.png

I hope you can see what im talking about...i guess that those grey pixels at the bottom of the words that make the "depth" thing.How can i make that effect?

How can i make the url bar white again? 

Thats just it...sorry for being annoying and as i said i completely understand if its to much work and is not worth the time. 

Thanks again for the awesome skin! :heart:

**Comment by Asphira** [comment]
This issue will be fixed shortly

**Comment by DirtDiglett** [comment]
These have been fixed in recent commits.
