### ISSUE TITLE
Recent Players on Overlay

### ISSUE THREAD

**Issue by Braguetto** [DirtDiglett/Pressure-for-Steam#125]
Up until the last version, the overlay had a button to the Players window. That window shows people who you've played recently and it is very useful, but with the last update, that option isn't available anymore.

Is it possible to add it again?

The attachment is the default version of the referred window.
![aaaa](https://cloud.githubusercontent.com/assets/10051716/5269430/b8a5d50e-7a49-11e4-9fa8-964b567cdd77.jpg)

Edit.: Even if it's not possible, thank you, the skin is amazing!! :D

**Comment by Jorchking** [comment]
ConnorNg Well is too useful for me, I use that every time I need to see players, that isn't useful for you doesn't mean isn't useful for the rest people.

**Comment by Js41637** [comment]
Well its not that it isn't useful to him its that it is extremely broken and 90% of the time not accurate or updated with actual recent players.

**Comment by DirtDiglett** [comment]
As @Js41637 has said, I am NOT saying that it's not useful at all.. It's that the in-steam version is very buggy and Valve have given up on fixing it, instead opting to do it properly on their website instead. When I can add buttons to the overlay that link to a website, I will add it back as a link to the website version.
