### ISSUE TITLE
New "Shared by" text is cut off

### ISSUE THREAD

**Issue by Zerathos** [DirtDiglett/Pressure-for-Steam#126]
http://i.imgur.com/9oxwkSJ.png

It's cut off all along the bottom, and also doesn't handle long names. The full name is Anyasia Lightbringer, but as you can see it cuts that off early.

**Comment by DirtDiglett** [comment]
I plan on doing a bit of re-working of the heading area for the game details page so will try to fix this more elegantly during this.

**Comment by DirtDiglett** [comment]
Should be 100% fixed :+1:
