### ISSUE TITLE
[Beta] Streaming/Broadcast Window button

### ISSUE THREAD

**Issue by Js41637** [DirtDiglett/Pressure-for-Steam#131]
Picture not needed cause it's like all the other buttons but the window only pops up when you request to watch a friends game via friends list menu, if you watch a broadcast on the community page, you don't get a pop-up window.

**Comment by Asphira** [comment]
I think this is intentional

**Comment by Js41637** [comment]
The popup that opens with unformatted buttons to close/minimize?

**Comment by DirtDiglett** [comment]
Can you please provide a picture of this, even though it's 'the same as the other button issues' I am a visual person so it's easier to fix if I can *see* the dialog window that has the issue and this also ensures I am fixing the right one :+1:

**Comment by Js41637** [comment]
Ok well i'm not sure if this is just like a general steam popup window or is a specific broadcasting window but in the friends list and right click on someone and click 'Watch Game' you get a popup like this;
![image](https://cloud.githubusercontent.com/assets/6258213/5645059/d0c068ca-96be-11e4-943a-afe7f7be20fa.png)

**Comment by DirtDiglett** [comment]
Cheers for the details, I'll work on it with all the other current open issues :smile:

**Comment by DirtDiglett** [comment]
@CaptainMagma fixed this for me a while back, forgot to close this.
