### ISSUE TITLE
I think its a bug and a sugestion

### ISSUE THREAD

**Issue by Holly-Chan** [DirtDiglett/Pressure-for-Steam#132]
I dont know if this is intended or not but here it is: the friends window is casting a weird shadow when you put it over the client window.
Here is the image:

![sem titulo](https://cloud.githubusercontent.com/assets/9482398/5329763/6cde630e-7da8-11e4-8502-c2671980372b.png)

I've also marked the fact that the shadow of the bar that tells you how many friends are online/playing needs to be extended a little to the left. 

**Sugestion**

Remeber #31 Tweak#4? Now that the background is grey instead of black, you might wanna put the shadow of a game's grid back to add that nice effect of "floating over".

I sugested that tweak before because i think it didn't make sense a "white shadow" on a black background, but now that its grey instead of black you might wanna give it a try and see if it loooks better, totally up to you.

Thats it, thanks again for the awesome skin !

**Comment by Asphira** [comment]
This is being removed in my newest pull request to Dirt, as well as other fixes :)

**Comment by DirtDiglett** [comment]
Yeah this was a quick experiment I did to try to apply some nicer shadows for them but then it created this weird zebra effect :(

**Comment by Js41637** [comment]
Just a note there does still seem to be a very tiny remnant of this bug, is hardly even noticeable, not sure if still bug or something.

![image](https://cloud.githubusercontent.com/assets/6258213/5645140/ea5823b2-96bf-11e4-99ef-e64ae7170e16.png)

**Comment by DirtDiglett** [comment]
Damnit @Asphira. You don't even fix the bug you just hide it hahahaha
