### ISSUE TITLE
Broadcast Chat WIndow

### ISSUE THREAD

**Issue by nuggs** [DirtDiglett/Pressure-for-Steam#135]
Not sure if you're supporting the beta client or not but it doesn't appear to be possible to open the broadcast chat window.

The group of buttons(Watch, Open Chat, Settings and Stop) are not available(From the overlay).  :(

![broadcast-chat](https://cloud.githubusercontent.com/assets/39425/5350931/72b8e8da-7f01-11e4-9b17-07cba4fb9777.png)

**Comment by DirtDiglett** [comment]
I'll be honest and say that i'm not sure at this stage how Pressure will support the broadcast feature... I'll need to have a think on the best way to work this.

**Comment by FlaminSarge** [comment]
@DirtDiglett Is there any update on this? If not, I was going to give it a try, but if you do have any work started on it, could I take a look?
