### ISSUE TITLE
Error with 'Shared Library' game

### ISSUE THREAD

**Issue by Zexorz** [DirtDiglett/Pressure-for-Steam#136]
![image](https://cloud.githubusercontent.com/assets/6225233/5403360/93034120-818c-11e4-898d-b81ddbf80b88.png)
![image](https://cloud.githubusercontent.com/assets/6225233/5403378/beac350c-818c-11e4-9c98-fd1c984959d1.png)

**Comment by DirtDiglett** [comment]
I'll work on fixing this.

**Comment by DirtDiglett** [comment]
Ok, I was trying to fix this and can't get these windows to pop up. Can somebody please explain to me how to get them to appear so I can fix this?

@Zexorz

**Comment by DirtDiglett** [comment]
This is fixed as seen here:http://puu.sh/gXc7F/a00daab96d.png
