### ISSUE TITLE
Group chat overflow

### ISSUE THREAD

**Issue by vegetabol** [DirtDiglett/Pressure-for-Steam#137]
There isn't a scroll bar for chat messages in group chats to see previous messages, but is present to browse the members list.

**Comment by Asphira** [comment]
It is also missing in default chat, this is something I should be fixing shortly with my new update coming shortly

**Comment by DirtDiglett** [comment]
Yeah it dissappeared at some point that I didn't notice so didn't really know where to start reverting changes to find the cause... That's @Asphira's job haha
