### ISSUE TITLE
Steam Emoticons Cut Off & Off Centre

### ISSUE THREAD

**Issue by Js41637** [DirtDiglett/Pressure-for-Steam#138]
![image](https://cloud.githubusercontent.com/assets/6258213/5427090/b4664ec0-83da-11e4-803d-21bd6d75ae23.png)

**Comment by Asphira** [comment]
Not fixable, steam limitation

**Comment by DirtDiglett** [comment]
As @Asphira mentioned; This bug is difficult to fix. If I fix this (which I have) it breaks the menu dropdown in chats instead. It ended up being a one-or-the-other situation that can't be solved due to the way Valve implemented the silly emoticon popup.

**Comment by FlaminSarge** [comment]
This was fixed by https://github.com/DirtDiglett/Pressure-for-Steam/commit/a40212207e03c23867d056bbfee3f95174b0da4d, right?

**Comment by Js41637** [comment]
Yes this is fixed although there are still some edge cases i've noticed where they are still out of line but then sometimes it's fine.

**Comment by DirtDiglett** [comment]
Yeah I fixed it because Valve included the control names for the emoticon popups inside the new Broadcast layouts, which let me target them directly :+1:
