### ISSUE TITLE
Two window minimize/close issue - Restore a backup/CD key window

### ISSUE THREAD

**Issue by Dooogurt** [DirtDiglett/Pressure-for-Steam#140]
Title! ~

![issue1](https://cloud.githubusercontent.com/assets/10239012/5499464/2bedad5a-86fe-11e4-9dea-be29a178c15a.png)

![issue2](https://cloud.githubusercontent.com/assets/10239012/5499465/307becb0-86fe-11e4-9371-5e5d8916b485.png)

**Comment by Dooogurt** [comment]
Just wanted to add that the "Join group chat room" is getting cut off in the right click menu for a group.
![2015-01-05_20-49-34](https://cloud.githubusercontent.com/assets/10239012/5623164/a177cf16-951c-11e4-8985-29181afba314.png)

**Comment by DirtDiglett** [comment]
First screenshot one is part of a Valve-created Steam bug so I cannot fix that.

Second one is fixable so i'll work on that.

Third one is due to an experiment to fix a few other issues and wasn't reverted properly. It'll be fixed when #137 is fixed.

**Comment by DirtDiglett** [comment]
These were fixed by a clever solution provided by @CaptainMagma and I forgot to close this, closing it now.
