### ISSUE TITLE
Can't see cloud usage

### ISSUE THREAD

**Issue by WEGFan** [DirtDiglett/Pressure-for-Steam#143]
In normal skin, there is a label which displays how much cloud storage is used, but it doesn't shown in pressure skin.
![qq 20150102184421](https://cloud.githubusercontent.com/assets/7558201/5595503/75a27946-92af-11e4-8f43-2059409f0581.png)
![qq 20150102184349](https://cloud.githubusercontent.com/assets/7558201/5595504/75b1ce46-92af-11e4-97eb-3452fa412c39.png)

**Comment by Zerathos** [comment]
Huh, I wonder what commit that got broken in, because I could have sworn I've seen that working in Pressure before. Just went through checking a variety of installed and uninstalled games, EDGE included, and didn't see it on any of them.

**Comment by Asphira** [comment]
I will add that in if i find it :)

**Comment by DirtDiglett** [comment]
Don't need to worry yourself @Asphira I fixed it. It was just a bit of confusion about how sometimes Steam seperates the Checkbox control from the checkbox label and othertimes it combines them.
