### ISSUE TITLE
In-Game settings - FPS counter implementation

### ISSUE THREAD

**Issue by id310791** [DirtDiglett/Pressure-for-Steam#145]
Ubuntu 14.10 and Windows 8.1 with latest beta client.
After latest update FPS checkbox is "broken"(not implemented):
![2015-01-03_15-18-49](https://cloud.githubusercontent.com/assets/9195693/5602403/6ba4925a-935c-11e4-9380-6309b1c11618.png)
![settings_008](https://cloud.githubusercontent.com/assets/9195693/5602409/aafa4ac6-935c-11e4-8a6a-07ae1c79fc17.png)

**Comment by fwinest-JediThug** [comment]
I've made a temporary fix for it, but it doesn't look nice, hopefully @DirtDiglett is going to update his skin accordingly.

save this file to ...\Steam\skins\Pressure-for-Steam-master\resource\layout\

https://gist.githubusercontent.com/fwinest-JediThug/3fc1bf14b20f58eb31af/raw/1c466ea4e415539f1ba550b1b6b55b9ad4547616/subpaneloptionsingame.layout

**Comment by sebj** [comment]
As of the latest beta, there's a dropdown menu for in-game FPS counter.. Off, or on with locations.
![](http://i.imgur.com/ZlXdO4C.png)

**Comment by DirtDiglett** [comment]
I've updated the skin to use the dropdown menu the latest beta added.
