### ISSUE TITLE
Steam Beta show in-game FPS option

### ISSUE THREAD

**Issue by gla3dr** [DirtDiglett/Pressure-for-Steam#147]
I don't know if you are worried about new Steam Beta options working properly, but if you are, there is a new one that could be added. The option to show in-game FPS is now available in the settings window as you can see below under the browser home page setting:

![ss 2015-01-05 at 12 30 26](https://cloud.githubusercontent.com/assets/6866792/5609967/23969b82-947b-11e4-986c-edc440e2fd43.png)

Currently, with Pressure, it shows up at the top of the window like this:

![ss 2015-01-05 at 12 29 12](https://cloud.githubusercontent.com/assets/6866792/5609975/3c2a6296-947b-11e4-8985-e912bf43a9a3.png)

**Comment by Js41637** [comment]
This is a duplicate of issue #145.

How did you miss it?

**Comment by gla3dr** [comment]
Oh wow I must be blind. My bad.
