### ISSUE TITLE
Padding on the selectable thingys in Settings

### ISSUE THREAD

**Issue by Js41637** [DirtDiglett/Pressure-for-Steam#148]
I don't even know what to call them but these boxes below would probably benefit from some small padding on the left if possible where text the text is right on the border.

![image](https://cloud.githubusercontent.com/assets/6258213/5645232/f3783a6c-96c0-11e4-83d2-5fc72f60345b.png)

Other areas like this include `In-Home Streaming`, `Family` & `Music` settings pages.
EDIT: Other locations include in `Game Properties` under the `DLC` Tab.

I think what these things should look like should be similar to how the `View CD Key` popup displays the key with padding on the left sides.

![image](https://cloud.githubusercontent.com/assets/6258213/5645405/151f563a-96c3-11e4-94d8-961e7b758d1c.png)

**Comment by Asphira** [comment]
I believe I can do this to some of them, just not all, will look into it
