### ISSUE TITLE
Padding on Buttons in Servers window

### ISSUE THREAD

**Issue by Js41637** [DirtDiglett/Pressure-for-Steam#149]
In the `servers` view window the buttons are quite small, seem to be lacking padding

![image](https://cloud.githubusercontent.com/assets/6258213/5645292/ddfbcb30-96c1-11e4-9c2b-2d7290177147.png)

The buttons found while viewing game info are what they should be

![image](https://cloud.githubusercontent.com/assets/6258213/5645298/efc9f562-96c1-11e4-8d2d-72b7fcb407bb.png)

**Comment by Asphira** [comment]
Hmm yeh, the buttons appear a little smaller then they should, thanks for reporting the issue,

**Comment by DirtDiglett** [comment]
Yeah this is just a temporary thing to get it working. That dialog is a bit spastic all over.

**Comment by FlaminSarge** [comment]
It seems like the buttons 'fix' themselves whenever the 'Change filters' stuff is open.
