### ISSUE TITLE
[Bug] View Server Info - Join Game - Auto Retry Crash

### ISSUE THREAD

**Issue by Js41637** [DirtDiglett/Pressure-for-Steam#150]
When you are in the `View Server Info` popup window and you try to join a full server, the `Auto-Retry` button appears however upon pressing it it crashes my Steam Client.
Also pressing it WHILE in a game AND through the Overlay, it crashes the Steam Overlay.

![image](https://cloud.githubusercontent.com/assets/6258213/5645320/416a4098-96c2-11e4-81c9-bb339abc9b49.png)

Is this a bug with the Skin?

**Comment by FlaminSarge** [comment]
I also get this, and only when using Pressure, so you're not alone.
