### ISSUE TITLE
Friends window has too much white space and can't be made smaller

### ISSUE THREAD

**Issue by notnsane** [DirtDiglett/Pressure-for-Steam#151]
In the Friends window, there's too much extra space to the right, and it can't be made smaller with the resizing options:

http://i.imgur.com/QEP7bpr.png

It's almost half of the Friends window. We should be able to make it smaller.

**Comment by Zerathos** [comment]
Look up at the top there. The window ends at the search bar. You can't make it smaller than that without shrinking the search bar and/or the Friends and Groups buttons, which can't be dynamically done by a skin.

**Comment by notnsane** [comment]
Is there any way of moving either the buttons or the search bar one level up or down? That will solve the issue.

**Comment by Asphira** [comment]
I am not quite sure what you mean? can you please create a mockup image and then i can see if me and Dirt can make it happen

**Comment by Asphira** [comment]
What I might be able to do, is force the window to be somewhat larger, (not by much maybe 20 pixels, and push it across accordingly, would this do what yo uare after?

**Comment by notnsane** [comment]
Original: http://i.imgur.com/u8uPqOU.png
Mockup #1 with better horizontal margin (less "white/blank" space): http://i.imgur.com/YFCK9Nw.png
Mockup #2 (Mockup #1 + different Search bar placement): http://i.imgur.com/GXtGh99.png

Horrible mockups but, hey, they're mockups, you get the idea =P

**Comment by CorruptComputer** [comment]
I like #2 better

**Comment by Asphira** [comment]
I might muck around with mockup #2 as mockup #1's search bar I feel would be to small, I should even be able to make the search bar scale with window size (horizontally at least)

**Comment by DirtDiglett** [comment]
Search bar is WAY too small in Mockup 1. Mockup 2 is what I was considering already and I'm happy for that to happen. @Asphira if you do this make the search bar have a maximum-width of about 350px because there is a maximum amount of character available in it anyway and having a 50000px wide search bar is just silly.
