### ISSUE TITLE
Game "Status" (Online, In-Game, Away, etc.) text font size has legibility issues

### ISSUE THREAD

**Issue by notnsane** [DirtDiglett/Pressure-for-Steam#154]
Hi, this might be a personal issue (not perfect eyesight), but this font size is too small to be readable from a mid-distance (on Windows platforms, might be different on Mac).

http://i.imgur.com/1AYi5ge.png

One more point on the font should solve the issues. Again, it might be a personal issue, but per example, try to read the letters "nlin" individually from the "Online" word, they are barely legible from a recommended distance.

**Comment by Asphira** [comment]
I will discuss with Dirt, as I only help fix up the skin and edit it, I do not generally make legibility fixes

**Comment by DirtDiglett** [comment]
I can read it legibly standing a meter or two away from my screen, but for the sake of others I'll have a look at enlarging it slightly.
