### ISSUE TITLE
Music icon in search is overlaid by search clear icon

### ISSUE THREAD

**Issue by Zerathos** [DirtDiglett/Pressure-for-Steam#159]
![](http://i.imgur.com/xcyMRCb.png)
It normally looks [like this](http://i.imgur.com/A72rHfz.png), but when you type in anything into the search box, the x to clear the contents of the search sits on top of it and makes it look messy. Also, might just be me, but the music icon looks a tad too far right and up

And while I'm at it, is "Albums" supposed to look like that? It's a drop-down list, like the one to the left of it, but looks like it's just a label instead. The arrow next to it is a button as well. Don't know if that's intentional or just something that hasn't been gotten to because you haven't worked much on the Music interface yet though.

**Comment by FlaminSarge** [comment]
Do you have a screenshot handy for how default Steam does it?

**Comment by DirtDiglett** [comment]
Not much work has been done on the music stuff yet, I believe @Asphira was going to do some heavy work on it sometime soon.

**Comment by Zerathos** [comment]
>Do you have a screenshot handy for how default Steam does it?

It doesn't have the music icon in the search box.
![](http://i.imgur.com/QBt4Sew.png)

**Comment by FlaminSarge** [comment]
That music icon is actually supposed to open the Music player. It conflicts with the current search bar positioning, which is why one or the other might show up as the one that's on top.

**Comment by FlaminSarge** [comment]
Zerathos, check out the updated skin and see if it works out well. Leave another comment if it doesn't, and Dirt will reopen the issue.
