### ISSUE TITLE
Search bar on small mode

### ISSUE THREAD

**Issue by CorruptComputer** [DirtDiglett/Pressure-for-Steam#163]
http://i.gyazo.com/54121e88e4ac28ee7c4219942c793508.png

It looks a little broken to me.

**Comment by Zerathos** [comment]
Pull request #162 ought to fix that.

**Comment by DirtDiglett** [comment]
@CaptainMagma has been kind enough to submit a fix for us and I've merged it in to the main branch so doing a re-download of the latest version should sort it all out.
