### ISSUE TITLE
Search bar on small mode too low

### ISSUE THREAD

**Issue by CorruptComputer** [DirtDiglett/Pressure-for-Steam#166]
http://i.gyazo.com/7f01ed59394ad9e84da4ed8c05db2ac2.png

The left is the search bar on small mode, and the right is the friends list. The small mode one is a few pixels too low.

**Comment by DirtDiglett** [comment]
Doing anything on small mode is very low on the priority list, the changes that get it functional were added by community members so this probably won't be done for a while

**Comment by CaptainMagma** [comment]
I'm submitting a pull request to fix this very soon @CorruptComputer

**Comment by DirtDiglett** [comment]
@CaptainMagma has fixed it for us :+1: . Closing issue.
