### ISSUE TITLE
html findbar not styled

### ISSUE THREAD

**Issue by CaptainMagma** [DirtDiglett/Pressure-for-Steam#167]
The border surrounding it isn't aligned right, not sure if the border is supposed to fade out from left to right, there are no custom arrow buttons used for it (not sure if that's intended), and the number of instances found is placed behind the search bar.

![](http://i.imgur.com/xw0LIof.png)

Edit: Well I restyled it but I don't know how you want it to look exactly. With the way it's styled now, the search bar is too small in my opinion and does not leave room for some of the larger find count numbers. I would suggest deleting the "Search this page" text to have a larger search bar and more room for the find count.

![](http://i.imgur.com/mnkM4Ri.png)

Edit 2: Here it is without the "Search this page" text.

![](http://i.imgur.com/fATH43k.png)

**Comment by DirtDiglett** [comment]
This is something I had on the back of my mind a while ago but forgot entirely.. I definitely want this to look much nicer and your mockups are close to what I have in my head for doing with it. I'll work on it very shortly.

**Comment by CaptainMagma** [comment]
Alright well if you need the edited files just let me know.

**Comment by DirtDiglett** [comment]
@CaptainMagma I forgot to actually submit the comment on this, oops! Yeah if you want to shoot a pull request for it to save me some time that'd be lovely :)

**Comment by Js41637** [comment]
Fixed by commit 76693764428438a60578b40287c25f96c6590afa
