### ISSUE TITLE
New DLC field for Library view not supported

### ISSUE THREAD

**Issue by Zerathos** [DirtDiglett/Pressure-for-Steam#175]
There's a fancy new box for DLC in the Library view if you're using the Steam beta client. This is what it looks like under the default skin:
![](http://i.imgur.com/UYI3XwE.png)

This is what happens when you have Pressure:
![](http://i.imgur.com/7GCRANP.png)

The box doesn't show up, and instead you get this jumbled mess up in the corner there.

**Comment by DirtDiglett** [comment]
The awesome @Js41637 has sent me a fix for this, so I've merged it into the main branch. He's a pretty cool guy so thank him for that quick fix!
