### ISSUE TITLE
New DLC panel image hides, but the space does not shrink.

### ISSUE THREAD

**Issue by Zerathos** [DirtDiglett/Pressure-for-Steam#184]
[The latest update](http://steamcommunity.com/groups/SteamClientBeta#announcements/detail/204121794081465972) added the ability for the DLC image to disappear if the size of Steam's window shrinks small enough to preserve the amount of usable space. Here's what it looks like full size:
![](http://i.imgur.com/pceMala.png)

And here's what it looks like when it's small enough to shrink:
![](http://i.imgur.com/tVwmb7Z.png)

Pressure at full size:
![](http://i.imgur.com/vpDC4QK.png)

And Pressure when it's small enough to shrink:
![](http://i.imgur.com/XHFk69B.png)

No matter how small you make the window, the space the image occupied does not shrink.

**Comment by DirtDiglett** [comment]
@Js41637 was kind enough to provide a fix so it's been added.

closed.
