### ISSUE TITLE
In-home streaming button missing

### ISSUE THREAD

**Issue by Psycic101** [DirtDiglett/Pressure-for-Steam#191]
There is no option to stream a game via In-home Streaming when the game is installed on the "client" PC. The Stream button only appears when the "client" does not have the game installed. On the default skin there is an option to stream the game even if it is currently installed on the PC you're trying to stream to.

![in-home streaming](https://cloud.githubusercontent.com/assets/983667/6101879/ac6615bc-b034-11e4-993c-22cae053df3c.png)

In the attached picture, you'll see DOOM 3 shows Stream (it is not installed on "client" PC), Don't Starve only shows Play (it is installed on "client" PC) and under the default skin Don't Starve shows a dropdown menu to select Stream.

**Comment by DirtDiglett** [comment]
...Why would you stream a game you have installed ready to play?

**Comment by Psycic101** [comment]
Because the netbook I'm running it on only has a 1.2GHz dualcore processor, so I have it installed for playing away from home, but when I'm home I stream it from my gaming PC so that it runs smoother and my netbook then doesn't overheat. I play it on my netbook at home because then I can play from my bed or in the lounge, not from my office where the PC is

**Comment by DirtDiglett** [comment]
That's a pretty solid point, i'll see what I can do :+1:

**Comment by Psycic101** [comment]
Thanks a lot :) keep up the great work on a great skim. It's much appreciated :+1:

**Comment by DirtDiglett** [comment]
Should be all fixed up now :+1:
