### ISSUE TITLE
[Linux] Settings: Interface bug

### ISSUE THREAD

**Issue by id310791** [DirtDiglett/Pressure-for-Steam#194]
Latest Pressure git and latest Steam linux client:
![settings_012](https://cloud.githubusercontent.com/assets/9195693/6153801/425e918e-b238-11e4-80da-67cd14cd4064.png)
Ubuntu 14.10 x64, Steam package ver. 1423615084
P.S: on Windows everything is ok.

**Comment by Zerathos** [comment]
See #181. You are probably opted into the beta build on Windows.

**Comment by id310791** [comment]
I know that this bug was fixed. I'm using Steam beta on both platforms.

**Comment by Zerathos** [comment]
Then quite likely the beta build on Linux has the same missing option that the normal one does on Windows (I certainly don't see it in this screenshot). Can you switch to the default skin to check? It should be titled "Enable hardware video decoding, if supported (requires Steam to restart)." They might have left it out because they don't support fancy hardware features like that on Linux.

**Comment by id310791** [comment]
Yeah, you're right. Linux client lacks new options((
![settings_013](https://cloud.githubusercontent.com/assets/9195693/6155179/4a9b394c-b242-11e4-840b-22ec8b3bb024.png)

**Comment by Js41637** [comment]
Interesting, makes sense but I don't know how to fix this, I assume I can just make the button its own thing and put [!$OSX] or [$WINDOWS] but I can't actually test it.

If you want to test it copy this code into the `SettingsSubInterface.res` file located in the skin directory `steam\cached`


Just overwrite where it is in the file at line #343
```
		place {
			controls=AutoLaunchCheck,BigPictureModeCheck,DWriteCheck,UrlBarCheck
			dir=down
			start=SkinCombo
			y=10
			spacing=-4
		}

		place [!$OSX] {
			controls=H264HWAccelCheck
			dir=down
			start=UrlBarCheck
			y=-4
		}
		
		place {
			control="Divider2"
			dir=down
			start=H264HWAccelCheck
			y=10
			width=max
			margin-right=43
		}
```

**Comment by DirtDiglett** [comment]
if you use [!$OSX] then it will target both Windows and Linux, using [$WINDOWS] will only target Windows, and [$OSX] will target OSX... and Valve forgot to implement a [$LINUX] or [$NIX] one :-1: 

So the only way to specifically target linux is to have a "base" change, then overwrite it with an [$OSX] change for OSX and a [$WINDOWS] one for Windows, leaving Linux untouched with the original change.

Very silly but that's how it is right now.

**Comment by Js41637** [comment]
Makes sense considering the steam Skinning stuff hasn't been updated for ever to add Linux.

Anyway, made a test one, question though, because of how these work with start= , will a linux version of the next open also need to have the base and the OSX & Windows overwrites so that the Linux one doesn't start on one that doesn't exist.

```
		// Remove option for linux
		place {
			control=H264HWAccelCheck
			height=0
			width=0
		}
		// Readd button for Windows
		place [$WINDOWS] {
			controls=H264HWAccelCheck
			dir=down
			start=UrlBarCheck
			y=-4
		}
		// Readd button for OSX
		place [$OSX] {
			controls=H264HWAccelCheck
			dir=down
			start=UrlBarCheck
			y=-4
		}
		// Start divider at UrlBarCheck for Linux
		place {
			control="Divider2"
			dir=down
			start=UrlBarCheck
			y=10
			width=max
			margin-right=43
		}
		// Start divider at H264HWAccelCheck for Windows
		place [$WINDOWS]  {
			control="Divider2"
			dir=down
			start=H264HWAccelCheck
			y=10
			width=max
			margin-right=43
		}
		// Start divider at H264HWAccelCheck for OSX
		place [$OSX]  {
			control="Divider2"
			dir=down
			start=H264HWAccelCheck
			y=10
			width=max
			margin-right=43
		}
```

**Comment by DirtDiglett** [comment]
The way you've done it there should work and looks correct, but your overwrites to the button are leaving the width and heights of H264HWAccelCheck as 0 so they still won't appear.

**Comment by Js41637** [comment]
Oh yeah, still displayed fine for me though. What are the original widths and heights.

**Comment by Ryan-Trunten** [comment]
Confirmed on latest Windows version... not opted into beta.
Also on a few other settings options: Broadcasting
Not sure if related, but In-Game has some odd white box at top also.

**Comment by id310791** [comment]
But you need beta. It's expected bug on stable

**Comment by DirtDiglett** [comment]
@Ryan-Trunten You'll need to turn on Steam BETA to have the skin working. BETA has added a lot of changes to the Settings, and it's impossible to have the skin support both Beta and Non-Beta for big changes like this. So for this release we're supporting the beta change because it will become normal soon.

**Comment by Ryan-Trunten** [comment]
Strange.
Broadcasting is with public now, so, I wonder how and why it's any different.
I also don't recall the Interface setting window ever changing between beta and stable.
Was opted into beta just for broadcasting until it went public and then opted out.
Don't remember much changing in those settings.

**Comment by DirtDiglett** [comment]
The actual option that is causing this option isn't available on Linux or OS X and also not available in non-beta, it's new and has been added since Broadcasting.

**Comment by Ryan-Trunten** [comment]
Thank you for clarifying.
Sorry for any inconvenience.
I joined GitHub just for your skin.
