### ISSUE TITLE
Crash when signing in to Friends.

### ISSUE THREAD

**Issue by Zero-ELEC** [DirtDiglett/Pressure-for-Steam#195]
Everytime I sign in to friends with the skin on the Steam Client hangs indefinitely until I click on it and I'm prompted with the "This program has stopped working" prompt.
![crash1](https://cloud.githubusercontent.com/assets/10970783/6161963/d397104a-b22e-11e4-90d2-f32816427a10.png)
![crash2](https://cloud.githubusercontent.com/assets/10970783/6161964/d3aadb0c-b22e-11e4-9445-53f325822f62.png)

**Comment by Zerathos** [comment]
Duplicate of #165. Make sure you're on the latest commit. Also, if you're not already, try the Steam beta client, [this sounds like something that might address it](http://steamcommunity.com/groups/SteamClientBeta#announcements/detail/204121794096108438).

**Comment by Zerathos** [comment]
Well, looks like I finally got this crash this crash with the latest commit and beta update in place. Harder for me to test since I don't get it consistently like some other people, but yeah, it's still there.

**Comment by Zero-ELEC** [comment]
It seems to happen more often when Avatars are displayed. Have yet to experience it when they are tuned off.

**Comment by DirtDiglett** [comment]
I think what I'll experiment with is re-building the friendspanel.layout entirely and hopefully that'll fix the crashing :)

**Comment by DirtDiglett** [comment]
Give this latest change a try and let me know how you guys get on with the crashing.

**Comment by rsilverblood** [comment]
+DirtDiglett I don't seem to be experiencing the crashing when signing in to my friends list so far. Seems to not be a universal issue.

**Comment by DirtDiglett** [comment]
@Zero-ELEC Are you still experiencing the crash with the latest verion of the Skin and the current Steam Beta? Let me know please so I can either close this or take a further look.

**Comment by Zero-ELEC** [comment]
Yeah, works perfectly, sorry for the late response. Thanks for the great work!
