### ISSUE TITLE
Steam crashes after opening a second group chat.

### ISSUE THREAD

**Issue by AshTR** [DirtDiglett/Pressure-for-Steam#20]
I'm managing to replicate this issue every time I open Steam (and I actually remember having this same bug on Enhanced Steam way back when, caused me to switch skins then) and open two group chats, Steam will crash. This does not happen with the other skins I have like PixelVision or Air.

For the record as well, the group chats I open from the Friends list are the Reddit one, then the Steam Gifts (S.Gifts) chat.

**Comment by Asphira** [comment]
I have not managed to replicate this issue myself, At this current time I have about 6 friends chat windows open and 5 groups, 2 in the same window and the rest individual.
