### ISSUE TITLE
Friends buttons drop below container

### ISSUE THREAD

**Issue by Lynxaa** [DirtDiglett/Pressure-for-Steam#201]
http://i.imgur.com/nkgDApv.png
http://i.imgur.com/1zgw4bv.png
http://i.imgur.com/Lp5hvmc.png
http://i.imgur.com/VTxZN3e.png

**Comment by GOGO98901** [comment]
Duplicate of #198

**Comment by DirtDiglett** [comment]
Fixed this up.
