### ISSUE TITLE
Odd GUI and misalignment in tools section when things are grouped.

### ISSUE THREAD

**Issue by TekFolf** [DirtDiglett/Pressure-for-Steam#202]
![steam_2015-02-17_14-35-55](https://cloud.githubusercontent.com/assets/5775431/6229804/53e4508c-b6b2-11e4-8306-052caad3d88f.png)

Yeah, this has gone unoticed and I'm not sure what's causing it.
This issue is present at all resolutions but only occurs when things are grouped, for example Steam family sharing.

**Comment by Js41637** [comment]
Sorry so, normally, it's fine cause it doesn't look like that for me but if you use family sharing and they have a tool you don't it groups them which causes this issue?

**Comment by TekFolf** [comment]
Yes Js I believe this is correct.

**Comment by DirtDiglett** [comment]
Are you referring to the little collapser in the top left corner in the screenshot? Or something else i'm not seeing straight up

**Comment by FlaminSarge** [comment]
I believe you can achieve the same effect if you add one of these tools to Favorites, but a lot of it in general just looks misaligned. The top category bar (Title, *, Cloud, Status, Last Played) seems too small (height-wise), and the dark bars that are used as dividers on it extend down into the list area by a few pixels. The far right side of the headers doesn't line up properly with the category bar, either.

**Comment by TekFolf** [comment]
Yes, Sarge. You are correct. I believe this is all misalignment issues as for the odd graphical issue with the collapser pointed out by DirtDiglet I'm not sure what's causing that visual issue.

**Comment by DirtDiglett** [comment]
No worries guys, I'll sort them out soon and upload the fix.
