### ISSUE TITLE
Friends Window: Weird text alignment on buttons

### ISSUE THREAD

**Issue by Lynxaa** [DirtDiglett/Pressure-for-Steam#203]
http://i.imgur.com/SJLDboa.png
This just looks odd to me, personally it would look 100x better if the text was centered aligned.

That kind of goes for most small typed buttons with left aligned text.

**Comment by Js41637** [comment]
Not sure if possible, not an expert but looking over this friends panel, the styling is very complicated as there seems to be an awful lot of restrictions that Dirt had to work around just to get them like this.

**Comment by DirtDiglett** [comment]
Impossible, technically those aren't even buttons - I did a lot of hacking and trickery to make it look like buttons to fit the skin. They're tabs that have a bunch of hacked spacing, with overlayed borders from other labels and it's just a hacky soup. Sorry but it's not gonna happen.
