### ISSUE TITLE
Library Play Button: Icon -> Text Alignment & Header Alignment Issues

### ISSUE THREAD

**Issue by Lynxaa** [DirtDiglett/Pressure-for-Steam#204]
http://i.imgur.com/DnHM0Mj.png
http://i.imgur.com/9y6q0tD.png

http://i.imgur.com/VVHplpu.png
http://i.imgur.com/OekYlSy.png

**Comment by Js41637** [comment]
First issue, I'll have a quick look to try and fix.

Second issue, spoke to Dirt about this yesterday, apparently is a Valve bug and this cannot be fixed and the only way other skins have fixed it is by center aligning the text.

**Comment by Js41637** [comment]
Wait a minute, for the PLAY issue this is because you're not using the recommended font the skin is designed for. Unfortunately with Steams fixed width measurements, it is impossible to design anything to be 100% compatible with any font except the one it was designed for.

**Comment by DirtDiglett** [comment]
Please re-read the instructions regarding this skin: https://github.com/DirtDiglett/Pressure-for-Steam/blob/master/README.md

You need to install the Bebas font provided in the ZIP in order to fully utilize the skin. You've not installed the font which is why everything is out of alignment.
