### ISSUE TITLE
Achievements in Overlay

### ISSUE THREAD

**Issue by Luffeh** [DirtDiglett/Pressure-for-Steam#205]
Is there a possibility of removing the second achievement box when you reach 100% for a game?
Default Skin:
![](http://puu.sh/g1tku/a844f37132.jpg)

Pressure:
![](http://puu.sh/g1oSC/e417420e91.jpg)

**Comment by Js41637** [comment]
I don't think so...

**Comment by DirtDiglett** [comment]
In order to have the pretty little borders I had to overlay an image over them, but this also prevents the little hover tooltip... I may remove the border altogether.
