### ISSUE TITLE
Download Progress bars don't match

### ISSUE THREAD

**Issue by StamSolid** [DirtDiglett/Pressure-for-Steam#208]
The Game download progress bar and the bottom Steam Download Progress bar don't show the same percentage of completion. With the game's progress bar to be the wrong one.
![](http://i.imgur.com/e8Gxqrk.png)

**Comment by DirtDiglett** [comment]
That is weird, because a skin doesn't do anything related to this sort of thing and I don't experience the same issue. Are you sure it's not just your Steam and does it happen to *EVERY* download or just this one-off? If it continually happens switch back to default Steam and see if it happens there too please.

**Comment by StamSolid** [comment]
I changed back to default Steam skin and downloaded a game and the bars seems to be ok. Switched back to Pressure and now its ok there too. 
I noticed this more than a couple of times,  when games are being updated (mainly CSGO and Dota2). 
Hadn't tried to test it with fresh download of a game the same time as when the bars where off, but I don't know if that has anything to do with it.
Never happened to see this kind of thing before I install Pressure, that's why I thought that it might has to do something with it.
 But since you say that the skin doesn't touch those functions , I 'll have to believe you since I'm sure you know better. 
Maybe its a Steam Client bug or something.

**Comment by StamSolid** [comment]
@DirtDiglett It was Steam after all. Just caught it on action. Something flips when games updating.
![](http://i.imgur.com/xAvkijl.png)

**Comment by s0r00t** [comment]
This is not the problem.
If there's two or more games on the queue, the bar on the bottom will show progress of the total.
If there's only one game, the bar should be the same as the individual one (see first screenshot).
But I think that's a Steam problem, I've encountered this in Air.

**Comment by StamSolid** [comment]
Should be the same but its not. I know now that its a Steam issue and not the skins.
One game updating now.
![](http://i.imgur.com/8QWF4GX.png)
