### ISSUE TITLE
"Add a Friend" button on FriendsDialog probably shouldn't be used to round the corners

### ISSUE THREAD

**Issue by FlaminSarge** [DirtDiglett/Pressure-for-Steam#210]
...There's gotta be a better way.
Relevant lines: https://github.com/DirtDiglett/Pressure-for-Steam/blob/master/friends/FriendsDialog.res#L228

(That pixel is still clickable).

**Comment by DirtDiglett** [comment]
Yeah this was a compromise; The trickery is done by taking an existing control, usually a label, and making it look like something else but in this case I ran out of labels to use... And using the same label to do all 4 corners would render the tabs unclickable as the label would be on a higher Z Index.

**Comment by FlaminSarge** [comment]
Turns out you can actually click the column of pixels. There's another issue: the clickable area of the Friends and Groups 'buttons' isn't the same as what they appear to be. I assume it's another result of the 'trickery' since they're supposed to be pagetabs.

**Comment by DirtDiglett** [comment]
Spot on! More trickery to make them match the button look, There doesn't appear to be a way to increase the clickable width of the tabs, and there are gaps between them normally, so I had to use trickery to make them fit together... There's way too little actual customization available in Steam for skinners :(

**Comment by Js41637** [comment]
Think of them as easter eggs :)
