### ISSUE TITLE
Friend tag and groups bar don't fill width

### ISSUE THREAD

**Issue by GOGO98901** [DirtDiglett/Pressure-for-Steam#212]
Its fine when the window is small but as soon as its width is large the bar wont go all the way to the end
<img src="http://i.imgur.com/BkRQ9Jo.png" />

then
<img src="http://i.imgur.com/0FBjUbZ.png" />
<img src="http://i.imgur.com/qQOiMXj.png" />

**Comment by Zerathos** [comment]
It was just shrunk a few days ago to allow the minimum size of the window to be smaller. It can't adjust dynamically to match whatever size you have. Best you can do is use the old files to have the larger version instead. Maybe going forward it could be an option to have a "compact" and "large" friends list though, and have the user choose a file or use a program to switch between them like Metro does.

**Comment by GOGO98901** [comment]
okay
