### ISSUE TITLE
No title in table header in recent players window

### ISSUE THREAD

**Issue by LordFatBastard** [DirtDiglett/Pressure-for-Steam#213]
![](http://i.imgur.com/N5sgzcu.png)

There is no title text in the highlighted table cell in the window that displays players from recent servers.

**Comment by Js41637** [comment]
Outside of our control, this is how Steam has it.

**Comment by DirtDiglett** [comment]
That's because that's the column for the Avatar, default Steam is the same. This isn't an issue. Closing as such.That's because that's the column for the Avatar, default Steam is the same. This isn't an issue. Closing as such.
