### ISSUE TITLE
[Offline Mode] Friends window looks weird

### ISSUE THREAD

**Issue by Idearum** [DirtDiglett/Pressure-for-Steam#215]
The Friends window looks a bit weird with missing UI components when you're running Steam in Offline Mode.

Example:
![image](https://cloud.githubusercontent.com/assets/10578344/6339687/9dc6fb40-bbb8-11e4-8074-bc741ff68361.png)

**Comment by DirtDiglett** [comment]
Because when you're offline it cannot load the avatar, there is nothing to search and no tabs available. What do you expect to happen here?

**Comment by Idearum** [comment]
Mostly, something where the tabs is positioned to "stuff" the weirdly black area that clashes with the rest of the design. The lack of an avatar or search field is a non-issue since it doesn't contract with the surrounding or underlying design.

**Comment by Js41637** [comment]
These are issues that are out of out control, Skins are very limited in what they can do, we cannot create separate styles for offline and online.

**Comment by FlaminSarge** [comment]
What button is the "Sign in to Friends" button? We could try sticking that in the space. I imagine right now it's one of the hacks used to round out the buttons.

**Comment by DirtDiglett** [comment]
That button does fill the space. The thing here is that Idearum is running Steam in Offline Mode, which never displays the "Sign in to Friends" button, this button only appears when the connection is lost or the user  sets their Friends status to Offline.
![zxcvxvvbxvccb](https://cloud.githubusercontent.com/assets/3527401/6380605/7cc3852e-bd86-11e4-8374-b2bb691ae5b2.PNG)
