### ISSUE TITLE
Some small UI bugs

### ISSUE THREAD

**Issue by joshdigit** [DirtDiglett/Pressure-for-Steam#216]
**#1 Detail View. After expand and collapse categories**
![scr_000pr](https://cloud.githubusercontent.com/assets/10910144/6411234/395ed190-be7f-11e4-835a-06a9961daacd.jpg)

**#2 Missing "Check for Steam Client Updates" and "Check for Video Driver Updates" in main menu**
![scr_001pr](https://cloud.githubusercontent.com/assets/10910144/6411312/edfc15ea-be7f-11e4-832f-ace191d2f537.jpg) ![scr_001or](https://cloud.githubusercontent.com/assets/10910144/6411366/5f4acd72-be80-11e4-815d-dfcaa8a45c9e.jpg)

**#3 Cropped words in some areas**

*Pressure*
![scr_002pr](https://cloud.githubusercontent.com/assets/10910144/6411401/b8a26042-be80-11e4-9722-b92c88051596.jpg)
*Original*
![scr_002or](https://cloud.githubusercontent.com/assets/10910144/6411404/be551246-be80-11e4-8f8c-124e22dee2cc.jpg)

*Pressure*
![scr_003pr](https://cloud.githubusercontent.com/assets/10910144/6411408/c86de406-be80-11e4-908f-086d237a7bbf.jpg)
*Original*
![scr_003or](https://cloud.githubusercontent.com/assets/10910144/6411410/ccc187a6-be80-11e4-8e23-6d527ddbaacd.jpg)

*Pressure*
![scr_004pr](https://cloud.githubusercontent.com/assets/10910144/6411417/e38bbe20-be80-11e4-991d-3994092c689e.jpg)
*Original*
![scr_004or](https://cloud.githubusercontent.com/assets/10910144/6411419/e7d78f5e-be80-11e4-890a-385ebacf702c.jpg)

**#4 Same bugs in Small Mode**
*Cropped text*
![008](https://cloud.githubusercontent.com/assets/10910144/6411554/63ca24ae-be82-11e4-9109-fd8ef418cd44.jpg)

*GUI bug when categories collapsed*
![007g](https://cloud.githubusercontent.com/assets/10910144/6411564/885b596e-be82-11e4-82d0-413f9e1b484b.jpg) ![007](https://cloud.githubusercontent.com/assets/10910144/6411568/8cdabd54-be82-11e4-964a-b20ada672417.jpg)

**Comment by GOGO98901** [comment]
"Check for Steam Client Updates" and "Check for Video Driver Updates" were both removed on purpose

**Comment by Js41637** [comment]
# 1 is a known bug , happens when opening and closing a tab that has a tab under it.

# 2 as @GOGO98901 mentioned, they have been removed as they just take up space and aren't really needed, if you want to check for an update (which you'd only really need if you're in the Beta Client) you can just restart Steam however if you really want them, add the code provided below into your `steam.menu` file located in `resource/menus` folder.

**Comment by DirtDiglett** [comment]
As @Js41637 mentioned, removal of those menu items is intentional.

All of these have now been fixed. Closing.
