### ISSUE TITLE
Chat Emote Selector Alignment Issues

### ISSUE THREAD

**Issue by Lynxaa** [DirtDiglett/Pressure-for-Steam#217]
<img src="http://i.imgur.com/54KHnjD.png"/>
<img src="http://i.imgur.com/LXg1aB7.png"/>

**Comment by Js41637** [comment]
What exactly appears to be the problem? The emotes should be in line but sometimes they don't either cause their loading or something, every time I've noticed this the next time I view them they seem fine.

**Comment by Lynxaa** [comment]
It's only a problem I get with this skin.
The default skin works perfectly fine for me.

"What exactly appears to be the problem?"
Look at the screenshots...

**Comment by Js41637** [comment]
OH lol sorry, I thought you meant the blue hover cause that was fixed.

**Comment by Js41637** [comment]
Well I can't find any way to move it over, might be outside the skins control.

**Comment by Js41637** [comment]
Sorry should have mentioned, it is like this for a reason, if the emoticons weren't moved over then their background hovers wouldn't line up which looks worse. Unfortunately there doesn't seem to be a way to move everything further to the right.

![image](https://cloud.githubusercontent.com/assets/6258213/6425817/adf12258-bf90-11e4-9f18-6fb9aefe7595.png)
