### ISSUE TITLE
"Steam Crashing when loading a group chat when there's a private chat open"

### ISSUE THREAD

**Issue by Js41637** [DirtDiglett/Pressure-for-Steam#223]
Taken from: http://steamcommunity.com/groups/pressureskin/discussions/0/610574106422171391/

"So I've had an issue with joining group chats. Mainly when I already have a chat with one of my friends open. Steam just decides to freeze up and crash.

This doesn't happen with any other skin, or vanilla Steam. My computer is not the beefiest, but it should have no trouble running a steam skin(GTX 660, AMD FX6300, 8gb RAM)

I'm not sure what's causing this, I've tried reinstalling the skin and even reinstalling steam, to no avail. I haven't seen anything about it so it could still somehow be on my end, although it might be worth looking into just in case."

**Comment by Js41637** [comment]
Apparently downgrading from the Steam Client Beta to the Stable Client stopped this crash happening.

**Comment by CorruptComputer** [comment]
This is a huge problem for me as well.

**Comment by CorruptComputer** [comment]
After the recent code cleanups this has stopped happening to me, could be due to less code being loaded and looked through at once. Commit 99715c038d229d9bd9dc0e4b43d4a2afadbad379

**Comment by DirtDiglett** [comment]
Woo! I did a lot of organizing and removal of redundant code so this is a pure accident but a happy one!
