### ISSUE TITLE
Buddy list searchbar input language label

### ISSUE THREAD

**Issue by M4he** [DirtDiglett/Pressure-for-Steam#224]
![inputlabel](https://cloud.githubusercontent.com/assets/1408105/6636592/e3cdd7a0-c971-11e4-955a-5925df87e1f9.png)
Just look at the screenshot, the input language label to the right doesn't seem to be skinned. Maybe it only shows up for me because I have 2 different inputs set up :)

Otherwise awesome work with this gorgeous skin :heart:

EDIT:
It's in the chat window's text box too:
![input](https://cloud.githubusercontent.com/assets/1408105/6637143/2b05b5de-c977-11e4-9629-17d8845b5d43.png)

**Comment by Zerathos** [comment]
See #56.

**Comment by DirtDiglett** [comment]
Out of curiosity, how does it look for you in other skins? IE: Metro, PixelVision, etc.?

**Comment by DirtDiglett** [comment]
Ignore the previous message, after experimenting with various skins and trickery it's something that cannot be changed.

**Comment by M4he** [comment]
Bummer. But thanks for looking into it!
