### ISSUE TITLE
Issue with "Watch Stream" 

### ISSUE THREAD

**Issue by PinguFace** [DirtDiglett/Pressure-for-Steam#225]
Moin Moin,

got a problem with the "Watch Game" over Steam...
If i click it, this just happen: http://puu.sh/gKDbM/367b2edb6d.png

so i can't watch it or can't close it.

*Sorry for my bad English .__.

**Comment by DirtDiglett** [comment]
Latest commit should fix this.

**Comment by DirtDiglett** [comment]
I'll close this as fixed, worked for me on the pull from yesterday.
