### ISSUE TITLE
Buttons are missing

### ISSUE THREAD

**Issue by smithmd** [DirtDiglett/Pressure-for-Steam#229]
I can explain better with pictures, but most buttons seem to be missing.

Installer screen is missing buttons:  
![install-no-buttons](https://cloud.githubusercontent.com/assets/3329968/6838774/5bb1fc8e-d335-11e4-8f9c-9eda2dc5edd9.PNG)

Settings screen is missing buttons as well:  
![settings-no-buttons](https://cloud.githubusercontent.com/assets/3329968/6838793/b2c8101c-d335-11e4-928f-a217272b1814.PNG)

**Comment by CorruptComputer** [comment]
This is not the case for me. Are you using the latest version of pressure and the steam beta update?

**Comment by smithmd** [comment]
I just did a git pull and when I have steam check for updates it says there aren't any.

From about steam:
Built Mar 23 2015, at 20:07:51
Steam package versions: 1427176184

**Comment by DirtDiglett** [comment]
I'm not able to test the skin myself for another 6 hours or so, but am currently in the process of cleaning up the code in the files and may have been my stuff up. Can you download a copy of the skin from before yesterday and tell me if the issue still occurs? If not, it's a stuff up I've done :+1:

**Comment by smithmd** [comment]
I had a copy from three days ago and it's happening on that one also.

**Comment by Js41637** [comment]
Oh really?, commit cf5f1cc1d446c703e3104601159ffcb8a0ea6545 should be fine. If you have the git shell installed you can just `git reset cf5f1cc1d446c703e3104601159ffcb8a0ea6545` to rollback to that commit or just download the skin from that commit

**Comment by smithmd** [comment]
I actually just found it. There's an extra closing brace in button.styles. I'll submit a pull request.

**Comment by smithmd** [comment]
That pull request also seems to fix #230

**Comment by Js41637** [comment]
:+1:

**Comment by DirtDiglett** [comment]
Thanks muchly for that, it's always either a rogue " or }. Merged in the pull. Closing the issues.
