### ISSUE TITLE
Right-click menu on library collapsed to one letter wide

### ISSUE THREAD

**Issue by smithmd** [DirtDiglett/Pressure-for-Steam#230]
Right click menu gets cut off:  
![shrunken-context-menu](https://cloud.githubusercontent.com/assets/3329968/6838826/1908f7ce-d336-11e4-99e9-da524bfafbbb.png)

**Comment by CorruptComputer** [comment]
This is not the case for me. Are you using the latest version of pressure and the steam beta update?

**Comment by Js41637** [comment]
Yes this is a recent, not recommended to use latest versions, use commit cf5f1cc1d446c703e3104601159ffcb8a0ea6545 instead or rollback with the GitShell with `git reset cf5f1cc1d446c703e3104601159ffcb8a0ea6545` in the directory
