### ISSUE TITLE
Some of buttons become broken with latest update

### ISSUE THREAD

**Issue by KIDINK** [DirtDiglett/Pressure-for-Steam#233]
![default](https://cloud.githubusercontent.com/assets/1337953/6852314/08d06c42-d3f5-11e4-95fe-564239847872.PNG)
Maximize button, for example.
Using latest steam beta, russian locale

**Comment by CorruptComputer** [comment]
I can confirm that this is happening on the latest commit. 99715c038d229d9bd9dc0e4b43d4a2afadbad379

**Comment by KIDINK** [comment]
I can confirm that too.
Fixed.
