### ISSUE TITLE
Empty invite notification window

### ISSUE THREAD

**Issue by KIDINK** [DirtDiglett/Pressure-for-Steam#237]
How to:
1. Get invited (CSGO, for example)
2. Use russian steam locale with latest steam beta + latest skin
3. Get this
![default](https://cloud.githubusercontent.com/assets/1337953/6881667/ad7a948a-d57a-11e4-8ef6-bc6669a0a44a.PNG)

**Comment by DirtDiglett** [comment]
Whoops! I left out a line and forgot to add it back. All fixed now.
