### ISSUE TITLE
Steam updating dialogue alignment

### ISSUE THREAD

**Issue by Psycic101** [DirtDiglett/Pressure-for-Steam#238]
When steam installs a Steam update (not for a game), this dialogue appears but the loading bar is in an awkward position. I think this only occurs when Steam downloads the update while being online and then installs the update while there is no available internet connection (although I could be wrong about this) but it's certainly occurred a few times on 2 of my devices.

![steam updater](https://cloud.githubusercontent.com/assets/983667/6904784/b0b50f68-d723-11e4-9798-8615555398ac.png)

**Comment by Js41637** [comment]
Yeah not too sure when this appears, it comes up sometimes and usually not for very long. Steam doesn't show anything while downloading an update in the background, there is the 'Check for an Update' Page that shows download progress (which can't be accessed in the skin) and restarting steam after an update or prior to the update being downloaded should show the normal downloading/installing Steam Update window which is a normal non steam window. And then this shows up, but not always with the loading bar.

**Comment by DirtDiglett** [comment]
@Js41637 This occurs when steam is updating during launch. It does this because it's the same dialog as the normal 'pre-load' one. 

Technically this is working as intended, but it isn't pretty so I am going to have another look at it after the other higher priority things.

**Comment by DirtDiglett** [comment]
I've re-done the splash screen so this is sorted out now and fits better.
