### ISSUE TITLE
Purple colors in latest pull

### ISSUE THREAD

**Issue by JustSomeDood** [DirtDiglett/Pressure-for-Steam#243]
I pulled the latest revision from master about 5 minutes ago and I got an eye full of purple

![pressure](https://cloud.githubusercontent.com/assets/10580982/6959650/17225ed8-d8d0-11e4-9e29-eba383cc31ca.jpg)

I am not willing to rule out an april fools thing.

**Comment by FlaminSarge** [comment]
I can't seem to reproduce this. Did you recently update any graphics drivers?

**Comment by JustSomeDood** [comment]
Not since I installed windows the other day, same graphics drivers and in the previous pull (right after the big code cleanup) it was fine, today..unicorn madness

**Comment by DirtDiglett** [comment]
@JustSomeDood I also can't reproduce this. See attached image: 
![capture](https://cloud.githubusercontent.com/assets/3527401/6960302/b1331974-d964-11e4-8f73-d5fa585c0895.PNG)


Perhaps delete and re-download the skin and confirm that it's not happening with default Steam and other skins too. Looks like a Valve VGUI bug.

**Comment by JustSomeDood** [comment]
Deleted skin, started steam with default skin, redownloaded pressure, placed in skins folder and activated it, still purple.  I just noticed for whatever reason it is saying i'm not in the steam beta (I thought I was as far as earlier this afternoon) so I re-enabled it and waiting for it to update steam to check the skin.

**Comment by DirtDiglett** [comment]
This was fun while it lasted. Take a look at the title of the commit that started this bug: https://github.com/DirtDiglett/Pressure-for-Steam/commit/60722125031c8c38fc4b695259da7c51a38f37ce

Download the latest version, it fixes it as well as adds lots of new fixes.

**Comment by JustSomeDood** [comment]
HA! as I said in the initial comment "I am not willing to rule out an april fools thing."
