### ISSUE TITLE
Add a bit more distinction from the background on the sides of dropdown buttons

### ISSUE THREAD

**Issue by J5lx** [DirtDiglett/Pressure-for-Steam#248]
Currently dropdown buttons seem to "merge" with the background a bit on their sides:
![A dropdown button](https://cloud.githubusercontent.com/assets/2063777/6961667/86eea61a-d92d-11e4-8cc8-d1c4f96d2451.png)
Maybe it's just me, but I find this to look quite "cheap". The regular buttons look better:
![A regular button](https://cloud.githubusercontent.com/assets/2063777/6961788/a40f39fc-d92e-11e4-8c6f-7f863e77e5d2.png)

**Comment by J5lx** [comment]
Yeah, that fixed it somehow... But why does a missing *font* cause the *buttons* to look different?

**Comment by DirtDiglett** [comment]
The buttons have padding applied for the inner content based on the font used, but if a height is defined it will clip outside of those bounds, that's why the outer dark lines are hidden, they go outside the bounds provided and are clipped.
