### ISSUE TITLE
[Linux] Maximize/close buttons divider 

### ISSUE THREAD

**Issue by id310791** [DirtDiglett/Pressure-for-Steam#250]
Tiny-tiny bug in main window :)
![steam_013](https://cloud.githubusercontent.com/assets/9195693/6969955/0d8b21b0-d97b-11e4-9250-75d17110e7ec.png)
P.S: Not affecting Windows 8.1 :)

**Comment by Js41637** [comment]
Actually this happens for me as well and I am on Windows 8.1

**Comment by Js41637** [comment]
The Steam Cog on the main client goes behind the buttons.

**Comment by DirtDiglett** [comment]
Try the latest commit for me and let me know how it goes.

**Comment by id310791** [comment]
Not good :)
![screenshot from 2015-04-06 12 08 11](https://cloud.githubusercontent.com/assets/9195693/7002593/c2f17bc6-dc55-11e4-8699-4743673fb603.png)

**Comment by DirtDiglett** [comment]
Oops! Give this new commit a try :)

**Comment by id310791** [comment]
Perfect :)
![screenshot from 2015-04-06 13 54 33](https://cloud.githubusercontent.com/assets/9195693/7003548/9b7a1eea-dc64-11e4-984f-80bbffda0888.png)

**Comment by DirtDiglett** [comment]
Wonderful! No idea why it broke for Linux all of a sudden. Nothing changed with the widths or positioning for these buttons, just made them partially transparent.

So random.

Oh well, fixed now. Closing :)
