### ISSUE TITLE
tiny issue

### ISSUE THREAD

**Issue by Holly-Chan** [DirtDiglett/Pressure-for-Steam#252]
![capturar](https://cloud.githubusercontent.com/assets/9482398/6982561/a86b01a0-d9e9-11e4-8f6e-3eadddb9780c.PNG) not aligned
 that is all :stuck_out_tongue_closed_eyes: 

thanks again for the awesome skin !

**Comment by FlaminSarge** [comment]
Thanks, alvr! I was worried about this when I put up the changes to that icon's positioning, since I don't have 0 there.
