### ISSUE TITLE
Login dialog password textbox glitch

### ISSUE THREAD

**Issue by PetrVOLF** [DirtDiglett/Pressure-for-Steam#257]
![2015-04-05_124502](https://cloud.githubusercontent.com/assets/11805537/6996603/8cbe02cc-db92-11e4-8d8d-eb33c59c3e4a.png)
![2015-04-05_124515](https://cloud.githubusercontent.com/assets/11805537/6996602/8cbcfd14-db92-11e4-8354-f3c7bb0a40c4.png)

Using latest, but the glitch is for me for quite some time, I hope I'm not the only one.
Username is OK, even selecting text is OK, but the password textbox gets on the bottom a glitch when getting focus and selecting the password is out of bounds of the textbox.

**Comment by FlaminSarge** [comment]
Yeah, I've got it too. I'll see what's up. It doesn't happen for the username box, either.

**Comment by DirtDiglett** [comment]
All fixed up.
