### ISSUE TITLE
Steam Workshop banner is messed up

### ISSUE THREAD

**Issue by peterbrinck** [DirtDiglett/Pressure-for-Steam#261]
In the downloads panel, the Steam Workshop banner is messed up..

![Steam Workshop Banner is Messed Up](https://cloud.githubusercontent.com/assets/6154068/7026994/57365ed0-dd4d-11e4-96f3-ab899ef4f67f.png)

**Comment by alvr** [comment]
I don't have this problem. I'm using the latest commit and W7.

![2015-04-07 17_50_31-steam](https://cloud.githubusercontent.com/assets/217315/7027227/bb8b23ec-dd4e-11e4-98d0-f6ed2948c748.png)

**Comment by peterbrinck** [comment]
Me too.. 

It's a bit weird

**Comment by MrAmos123** [comment]
I just tried uninstalling BETA, then going back into Steam BETA, but this problem persists.. 
![image](https://cloud.githubusercontent.com/assets/4959320/7029874/75b0c41c-dd58-11e4-81ce-b1fec497e9fd.png)

**Comment by DirtDiglett** [comment]
Delete the skin entirely, restart Steam on its own skin then reinstall Pressure fresh.

Looks like Steam is just not letting go of its cache.

**Comment by Js41637** [comment]
Steam Cache is the worst. Took me ages when I had a problem, there is actually 2 steam cache folders. One in steam and the other somewhere else in the system.

**Comment by peterbrinck** [comment]
Okay.. I'll try it

**Comment by DirtDiglett** [comment]
Figured it all out. Looks to be unique to Age of Empires, I couldn't reproduce it with any other workshop-enabled game.

I've fixed it up though. Because it's using the 'game' update panel rather than the 'workshop' one I've removed the banner because there's no way to make it match the actual workshop update one (The light blue with shadowing and such).

**Comment by peterbrinck** [comment]
Great!

I'll update right away and see if it's fixed
