### ISSUE TITLE
[Linux] Scrollbars bug

### ISSUE THREAD

**Issue by id310791** [DirtDiglett/Pressure-for-Steam#263]
Latest commit in Ubuntu 14.10, latest Steam beta:
![screenshot from 2015-04-08 21 06 54](https://cloud.githubusercontent.com/assets/9195693/7052016/a3524a1c-de34-11e4-958c-512bbb80fdeb.png)
![screenshot from 2015-04-08 21 07 50](https://cloud.githubusercontent.com/assets/9195693/7052018/a354a19a-de34-11e4-8ad6-49859d29e82a.png)
![screenshot from 2015-04-08 21 08 00](https://cloud.githubusercontent.com/assets/9195693/7052019/a3562b3c-de34-11e4-9733-c8eb885d4e2b.png)
But not for Library:
![screenshot from 2015-04-08 21 08 14](https://cloud.githubusercontent.com/assets/9195693/7052017/a354b4be-de34-11e4-91b7-8c4a0f90f8ac.png)

**Comment by alvr** [comment]
Ser #262.

**Comment by id310791** [comment]
alvr, oops :)
