### ISSUE TITLE
[Linux] Some fonts issues

### ISSUE THREAD

**Issue by id310791** [DirtDiglett/Pressure-for-Steam#264]
So it's not critical but is it possible to make some tweaks to this?
Ubuntu 14.10, latest commit, Steam beta
PS: Bebas and Noto Sans is installed manually and `fc-cache -fv` is executed :) 
Look at letter 'g' in this pic and URLs
![screenshot from 2015-04-08 21 07 06](https://cloud.githubusercontent.com/assets/9195693/7052299/6d3dcc10-de36-11e4-8519-84f852d4b073.png)
![screenshot from 2015-04-08 21 26 50](https://cloud.githubusercontent.com/assets/9195693/7052300/6d409c2e-de36-11e4-9523-72097c94f849.png)
![screenshot from 2015-04-08 21 26 58](https://cloud.githubusercontent.com/assets/9195693/7052301/6d4132ec-de36-11e4-93e5-1367d9f541a6.png)
![screenshot from 2015-04-08 21 27 04](https://cloud.githubusercontent.com/assets/9195693/7052302/6d420672-de36-11e4-96f8-da9b06c6bc94.png)
![screenshot from 2015-04-08 21 27 16](https://cloud.githubusercontent.com/assets/9195693/7052303/6d4437b2-de36-11e4-9e3c-9680fe56eb0c.png)
![screenshot from 2015-04-08 21 27 48](https://cloud.githubusercontent.com/assets/9195693/7052304/6d458eb4-de36-11e4-8df0-49c9d895eada.png)

**Comment by DirtDiglett** [comment]
Thanks for the in-depth report, I'll look at getting these sorted asap.

**Comment by id310791** [comment]
Thanks! 
Offtopic; Yesterday checked default skin....it's so lame compared to Pressure :) Thank you Mat and Asp for your work!

**Comment by DirtDiglett** [comment]
Want to give the latest commit a try for me and let me know how it looks? Your screenshots show me that for some reason it's rendering text REALLY large compared to how it should be so I've globally dropped the size a point which should also server to fix these problems.

**Comment by id310791** [comment]
Sorry at the moment I can't check because I'm at work. But first thing to do at home will be this. Also about font rendering. Yes. It was always bigger compared to other platforms.

**Comment by Js41637** [comment]
Linux always seems to be bigger in everything.

**Comment by id310791** [comment]
It's much better now. But In-home streaming is broken.
![screenshot from 2015-04-09 18 31 26](https://cloud.githubusercontent.com/assets/9195693/7070296/b8f384b4-dee6-11e4-8a18-b1672fb752de.png)

![screenshot from 2015-04-09 18 28 39](https://cloud.githubusercontent.com/assets/9195693/7070253/71cb2ba0-dee6-11e4-8830-002f6a81614f.png)
![screenshot from 2015-04-09 18 28 56](https://cloud.githubusercontent.com/assets/9195693/7070255/73b12b54-dee6-11e4-88f3-1000d195ada2.png)
![screenshot from 2015-04-09 18 28 43](https://cloud.githubusercontent.com/assets/9195693/7070256/76a6f92e-dee6-11e4-8f27-aec4c3d7600e.png)

**Comment by DirtDiglett** [comment]
Can you please send me a screenshot of In-Home Streaming on the default skin, there's something missing that the rest relies on to lay out that is present in Windows & OSX but not Linux and I can't tell by that screenshot alone unfortunately.

**Comment by id310791** [comment]
Here it is/
![screenshot from 2015-04-11 08 52 17](https://cloud.githubusercontent.com/assets/9195693/7100380/2fac6980-e028-11e4-9107-a11b5fc212ad.png)

**Comment by DirtDiglett** [comment]
Try latest commit please.

**Comment by id310791** [comment]
:)
![screenshot from 2015-04-11 09 23 41](https://cloud.githubusercontent.com/assets/9195693/7100475/8a55f4b0-e02c-11e4-9ac1-e9c8e96b00a6.png)

**Comment by DirtDiglett** [comment]
Awesome, I'll close this now since it looks like it's all working properly. (I've just changed the spacing on the streaming settings so "view support information" fits in the window.

**Comment by id310791** [comment]
Yay! :) Thank you.
