### ISSUE TITLE
Noto Sans is a horrifying font

### ISSUE THREAD

**Issue by CronosDage** [DirtDiglett/Pressure-for-Steam#265]
please revert to whatever it was before

**Comment by CronosDage** [comment]
also what was wrong with this scrollbar

http://i.imgur.com/n2qwnt7.png

**Comment by DirtDiglett** [comment]
I'm not changing the font away from Noto. 

Can you be more specific where you're experiencing that scrollbar issue? A similar issue existed last week but was fixed and I can't reproduce this.

**Comment by CorruptComputer** [comment]
I really like the Noto Sans. But I think the chat font should be changed.

**Comment by CronosDage** [comment]
the scrollbar fixed itself

whatever, I'll just clone the repo and swap out noto for helvetica neue
