### ISSUE TITLE
Displaced checkbox in Friend Notification Options

### ISSUE THREAD

**Issue by KIDINK** [DirtDiglett/Pressure-for-Steam#267]
1. Open your FriendList
2. Open context menu on any friend
3. Select Notification Options
4. You will notice that last checkbox is displaced to right

![default](https://cloud.githubusercontent.com/assets/1337953/7074392/b07b4990-df02-11e4-8583-6e7fee7a9eed.PNG)

**Comment by Js41637** [comment]
Wow Valve, how do you even manage to do this.
