### ISSUE TITLE
Check for Steam Client and Video Driver Updates options missing from menu

### ISSUE THREAD

**Issue by Nemecyst** [DirtDiglett/Pressure-for-Steam#271]
![checkforupdates](https://cloud.githubusercontent.com/assets/9501781/7089188/027f8200-df68-11e4-800c-89717c722279.png)

**Comment by GOGO98901** [comment]
Those were removed on purpose

**Comment by Nemecyst** [comment]
I think it would be useful to have them on there, on Linux, the client doesn't check for updates right away when a new update is released and having that option will at least provide a workaround.

**Comment by GOGO98901** [comment]
You can create a custom menu file
edit the file `resource/menus/steam.menu`
and the following code to the file where you would like the button to go
[`CheckForUpdates	{text="#steam_menu_checkforupdates" command="CheckForUpdates"}`](https://gist.github.com/GOGO98901/9c75256703bba3c06c00#file-steam-menu)

**Comment by alvr** [comment]
Edit `resource/menu/steam.menu` and replace the content with this: https://gist.github.com/alvr/91d5483da54298085e0a

**Comment by Nemecyst** [comment]
Thanks guys, this solves my issue.
