### ISSUE TITLE
Scroll Bar Unstylized

### ISSUE THREAD

**Issue by Frostwolfo** [DirtDiglett/Pressure-for-Steam#272]
![scroll bar](https://cloud.githubusercontent.com/assets/11674799/7099083/7dc4b574-dfb9-11e4-9ead-a5bf94cd4cef.png)
The scroll bar no longer fits the style. It seems to at least occur on the shop and community pages. The library and friends list seem fine.

**Comment by GOGO98901** [comment]
See #262
