### ISSUE TITLE
'Tools' tab won't parse properly

### ISSUE THREAD

**Issue by KIDINK** [DirtDiglett/Pressure-for-Steam#273]
Dno, is that steam beta bug or skin bug, but still have a look
![default](https://cloud.githubusercontent.com/assets/1337953/7100906/b3bf6a62-e044-11e4-86d5-d6c22b4ec9da.PNG)

**Comment by KIDINK** [comment]
BTW:
1. Open steam library
2. Switch from 'Games' type (middle dropdown menu) to 'Installed'
3. Install some tools
4. Inspect them.

**Comment by DirtDiglett** [comment]
It's a steam bug. Whenever you see words beginning with # in a Valve-owned program (Steam, Source Enginer, etc.) it's a placeholder for translated words. You're not normally meant to see them as they should default to English but sometimes things bug out and it shows them all the same.

Unfortunately this isn't a skin bug I can fix, it's an issue with default Steam. I don't experience it to the same level as you do, but this is what I see for every tool (Notice the purchase bit):

![steambug](https://cloud.githubusercontent.com/assets/3527401/7104630/5ecec04a-e132-11e4-9541-f10f67c4f628.PNG)
