### ISSUE TITLE
Workshop preview @ gamepage cuts creator's avatar

### ISSUE THREAD

**Issue by KIDINK** [DirtDiglett/Pressure-for-Steam#274]
![default](https://cloud.githubusercontent.com/assets/1337953/7100951/c3412460-e046-11e4-95bc-42fb56b61f9d.PNG)

**Comment by Js41637** [comment]
This is in the normal Games Details page right? I don't think avatars are even meant to be displayed there but I don't have this issue, mine displays just the name and rating, no avatars.

**Comment by KIDINK** [comment]
Some of them are displayed, some of them not.
Btw, i don't have this issue on default skin

//few hours later
![default](https://cloud.githubusercontent.com/assets/1337953/7101359/350aca7a-e05f-11e4-82aa-7870f8a15d7c.PNG)

**Comment by GOGO98901** [comment]
I am also experiencing this issue
But only on the csgo, all other games are fine even thought that I don't think that should be a problem

**Comment by DirtDiglett** [comment]
Ah, I was wondering what that control was for. It shows the avatar ONLY when the workshop item was submitted by a friend on your friendslist. I've fixed it up now so they'll show up in the top left of the item.
