### ISSUE TITLE
Chat box,steam friends list drag-ability 

### ISSUE THREAD

**Issue by Wiggin38** [DirtDiglett/Pressure-for-Steam#275]
Hi, 

I downloaded the most current version today. 

The space at the top of the chat window and friends list is the only place you can click to drag the boxes around. In the previous version you click anywhere in the blank space to move the windows around. Will be fixed in the future ? 

Secondly, this is more of a request. Is it possible to show the steam wallet when it is empty just with like $0.00 ? If so, I can do it myself if someone points me in the right direction. 

Really loving the skin. Thanks for all the hard work.

**Comment by DirtDiglett** [comment]
I've adjusted the vertical grabbing area to be easier, I thought I had already done it as it was on my to-do but must've forgotten.

In regards to the wallet. I'd love for it to show when there is $0.00 but Valve made it so it's 100% hidden when at $0.00 so I can't force it to appear.

**Comment by Wiggin38** [comment]
Hi, 

Thank you for the fix. 

That is quite thoughtful of valve. 

My only issues is that on certain pages there is a thick grey scroll bar instead of the sleek black one.  (Store,Profile. etc)

**Comment by FlaminSarge** [comment]
See #262 with regards to the scroll bars.
