### ISSUE TITLE
Lower active arrow becoming outlined (light contour), upper one doesn't (library sorting buttons)

### ISSUE THREAD

**Issue by KIDINK** [DirtDiglett/Pressure-for-Steam#279]
1. Open your library
2. Use 'List Mode' or open your 'Tools' tab.
3. Pos your mouse cursor on sort button
See this

1. ArrowUp
1.1 Non-active shows like 
![1](https://cloud.githubusercontent.com/assets/1337953/7137413/1ae98978-e2c2-11e4-93a4-86346592aa6a.PNG)

1.2 Active shows like
![2](https://cloud.githubusercontent.com/assets/1337953/7137415/1d661644-e2c2-11e4-9b5c-5ff855d031ad.PNG)

2. ArrowDown
2.1 Non-active shows like 
![3](https://cloud.githubusercontent.com/assets/1337953/7137418/217334a6-e2c2-11e4-805f-05d8a7cb4cca.PNG)

2.2 Active shows like
![4](https://cloud.githubusercontent.com/assets/1337953/7137419/23cd501a-e2c2-11e4-98b3-faa8b432d127.PNG)

Active arrows should be same. But for now, active up arrow isn't lighted, but active down arrow does.

**Comment by KIDINK** [comment]
This arrows are both active, that's what i mean
![2](https://cloud.githubusercontent.com/assets/1337953/7137481/a3a266f4-e2c2-11e4-9be8-dcf98eed5f80.PNG)
![4](https://cloud.githubusercontent.com/assets/1337953/7137482/a3a3472c-e2c2-11e4-89b6-905e50e16ca5.PNG)

**Comment by KIDINK** [comment]
![1](https://cloud.githubusercontent.com/assets/1337953/7137512/f9f8b15c-e2c2-11e4-8ea0-27aa7624112d.PNG)
![3](https://cloud.githubusercontent.com/assets/1337953/7137513/f9fa4dd2-e2c2-11e4-8f77-61afb8652e99.PNG)

**Comment by DirtDiglett** [comment]
Thanks for picking up on this! I've gone ahead and fixed all the arrow images to match so this is all sorted :)
