### ISSUE TITLE
A weird glitch

### ISSUE THREAD

**Issue by Holly-Chan** [DirtDiglett/Pressure-for-Steam#280]
So i've been having this glitch for some time now. Sometimes when i go to the settings, some part of the bottom of the window becomes black. Here is the image:

![sem titulo](https://cloud.githubusercontent.com/assets/9482398/7138002/d7ac11d6-e293-11e4-9528-0f8bb015a019.png)

The 2 thing is... when i hover the cursor over the black part it fixes itself , and the other thing is that it doesn't happen all the time so it is hard to reproduce the issue,it just...suddenly happens. I'm on Windows 7 x64.

Thats it, thanks again Diglet.

**Comment by alvr** [comment]
I can't reproduce this. Try using the beta version of the client.

**Comment by KIDINK** [comment]
Ye, same here.
In most situations the reason is stable client instead of beta.

**Comment by Holly-Chan** [comment]
i'll test with the beta client, will report back if i see it again.

**Comment by DirtDiglett** [comment]
100% No reason this should be happening. I had it once while I was on the stable client about a week ago and never happened again. Usually if something like that fixes itself on mouseover it's a glitch in steam rendering, rather than the skin.
