### ISSUE TITLE
Wrong icon positional using 'List View' mode

### ISSUE THREAD

**Issue by KIDINK** [DirtDiglett/Pressure-for-Steam#281]
First of all, this is normal mode (Details View)
![default](https://cloud.githubusercontent.com/assets/1337953/7147706/85240122-e305-11e4-8a53-53801bcc2c2d.PNG)
But if we switch to 'List View' mode - icons will cut off
![2](https://cloud.githubusercontent.com/assets/1337953/7147720/b1c422ca-e305-11e4-8df7-d50e08d1cbcc.PNG)

**Comment by Js41637** [comment]
Good eye, I've got a fix ready.

**Comment by DirtDiglett** [comment]
@Js41637 has sent me the fix, so it's part of the main branch now. Closing :)
