### ISSUE TITLE
Library Game Info screen needs some more padding

### ISSUE THREAD

**Issue by rydgeback** [DirtDiglett/Pressure-for-Steam#290]
Just noticed this today, the gap between "Game Info" and the launch instructions is very little. 
![untitled](https://cloud.githubusercontent.com/assets/11993780/7201844/16dc4b42-e51d-11e4-963f-2282b3916d70.jpg)

**Comment by KIDINK** [comment]
I can confirm that.
![default](https://cloud.githubusercontent.com/assets/1337953/7202120/e79f582e-e517-11e4-9207-5274cd0bca54.PNG)
