### ISSUE TITLE
Add non-steam game problems

### ISSUE THREAD

**Issue by GOGO98901** [DirtDiglett/Pressure-for-Steam#294]
![add a game](https://cloud.githubusercontent.com/assets/2751799/7215633/1046fc84-e5d9-11e4-97d1-8156249b8222.png)
- 1 - The select all tick box is to high
- 2 - The tick boxes on the sides are not centered
- 3 - When scrolling program clips through top and line appears (image bellow will explain)

![add a game2](https://cloud.githubusercontent.com/assets/2751799/7215642/4f751a30-e5d9-11e4-9890-1c02bb54d6fd.png)

**Comment by KIDINK** [comment]
I can confirm both.
Also that damn arrows... Upper active & non-active arrows are the same.
But Lower active & non-active doesn't.

**Comment by Js41637** [comment]
The arrow problem should be fixed, up and down arrows should be normal when you're not hovering over them however (at the moment) only the down arrow has a hovered version while the up arrow currently does not.

**Comment by DirtDiglett** [comment]
Thanks to @Js41637 this has been fixed and applied to the main branch. Closing.
