### ISSUE TITLE
Navigation arrow not centered on most buttons

### ISSUE THREAD

**Issue by KIDINK** [DirtDiglett/Pressure-for-Steam#297]
This is bug, right?

![1](https://cloud.githubusercontent.com/assets/1337953/7217532/8dd4f8b8-e638-11e4-97e2-e27d60f76ab9.png)
![2](https://cloud.githubusercontent.com/assets/1337953/7217533/8dda8a62-e638-11e4-8274-e1bde8e2d10c.png)
![3](https://cloud.githubusercontent.com/assets/1337953/7217534/8dde697a-e638-11e4-9bd9-6d2f0763b33e.png)
![4](https://cloud.githubusercontent.com/assets/1337953/7217535/8de3db8a-e638-11e4-9ccf-cd5d6652bbf5.png)
![5](https://cloud.githubusercontent.com/assets/1337953/7217536/8df7b524-e638-11e4-9e2f-a43fa5b58c19.png)

**Comment by KIDINK** [comment]
This arrow
![1](https://cloud.githubusercontent.com/assets/1337953/7217541/ae32e9e4-e638-11e4-8107-36c30b86fce3.png)

**Comment by Zerathos** [comment]
It's not possible to center them with the tools available to skins, see #19.

**Comment by DirtDiglett** [comment]
As Zerathos has mentioned, it's an unfortunate limitation in the way Steam handles widths that it's not possible to center this to all of the main navigation items across all languages. To compensate for this limitation I chose a horizontal offset that should make it work well for the most part.

Closing.
