### ISSUE TITLE
'Close invitation window' button should be bigger

### ISSUE THREAD

**Issue by KIDINK** [DirtDiglett/Pressure-for-Steam#299]
1. Get invited in any game
2. Open chat with person who you got invite from

Sometimes you can missclick on that close button and you will join game lobby.

**Comment by DirtDiglett** [comment]
I agree, the buttons are quite small in hindsight. I'll make them significantly larger when I get home from work :+1:

**Comment by KIDINK** [comment]
Thank you! <3
