### ISSUE TITLE
A couple visual errors

### ISSUE THREAD

**Issue by WildManiac** [DirtDiglett/Pressure-for-Steam#300]
Screenshot 1: Text in CD Key Window list to far over left and black line appears through highlight (assuming that is the highlight overflowing upwards into the headers)
![error](https://cloud.githubusercontent.com/assets/11233971/7222168/116c2fd2-e6d6-11e4-8377-9c65d13cfea7.png)

Screenshot 2: Scrolling all the way down in groups section of friends list does not give enough room for final group.
![error2](https://cloud.githubusercontent.com/assets/11233971/7223954/1e0f8de2-e6f9-11e4-8efd-30a79377f008.png)

**Comment by DirtDiglett** [comment]
Hi @WildManiac,

I've gone ahead and fixed the issues with the CD Key dialog, and also improved it in the process to match the Pressure visual style.

As for the friends dialog issue you've reported. This is a bug I was already aware of and unfortunately won't be fixed. I had to choose between having that 3 pixels at the bottom cut off, or have the buttons at the top look all spastic and went for the former.
