### ISSUE TITLE
New login menu wont remember last used username

### ISSUE THREAD

**Issue by KIDINK** [DirtDiglett/Pressure-for-Steam#301]
Topic name like it is.
Also menu wont remember 'Remember my password' checkbox status.
1. Login in account with enabled checkbox
2. Logout
3. Both login-password fields will be empty
4. Checkbox will be toggled-off.

**Comment by Zerathos** [comment]
I can't replicate this on my end. First things first, are you using the Steam beta client?

**Comment by KIDINK** [comment]
for sure

**Comment by Zerathos** [comment]
Hmm, well so am I, so that's not it. OS? Windows 7 here. Also, have you tested with the default skin yet?

**Comment by KIDINK** [comment]
Sorry.
I just tested it with vanilla skin and i got same problem here.
Steam won't remember any login parameters at all.

**Comment by DirtDiglett** [comment]
Closing as a non-Pressure bug.
