### ISSUE TITLE
CD Key Misalignments

### ISSUE THREAD

**Issue by CorruptComputer** [DirtDiglett/Pressure-for-Steam#303]
Using commit 6840f962bb33f65cf81e15c5c31c0e0f936152ba

![capture](https://cloud.githubusercontent.com/assets/5573038/7264226/0f69495c-e84f-11e4-9923-bbc7cb17d45f.PNG)

**Comment by CorruptComputer** [comment]
Oh and I forgot about this.

![capture](https://cloud.githubusercontent.com/assets/5573038/7264272/97d5b30c-e84f-11e4-9573-149c6071cf31.PNG)

**Comment by DirtDiglett** [comment]
This is what I get for not fully testing something before uploading it :-1: 

I'll fix this up shortly and upload a fix.
