### ISSUE TITLE
Overlay "Open chat" doesn't work

### ISSUE THREAD

**Issue by Xhayn** [DirtDiglett/Pressure-for-Steam#309]
Making a screenshot always pulls a black page, but I think this is simple enough.

Any time I broadcast a game, clicking "open chat" in the overlay does nothing. "Watch" and "stop" work correctly.

**Comment by FlaminSarge** [comment]
We're trying to figure this one out right now. We thought it appeared relative to the Open Chat button, but there were some counterexamples so now nobody's sure what's going on.
