### ISSUE TITLE
Text cuts off with different combination of window size and shortcut length

### ISSUE THREAD

**Issue by KIDINK** [DirtDiglett/Pressure-for-Steam#310]
Fullscreen 1440*900
![default](https://cloud.githubusercontent.com/assets/1337953/7315707/a7bea1fe-ea78-11e4-8fb0-6e1eebbe5f1f.PNG)

Minimal window size
![default](https://cloud.githubusercontent.com/assets/1337953/7315716/c25144d6-ea78-11e4-8262-f0031533e206.PNG)

**Comment by KIDINK** [comment]
Can someone confirm this?

**Comment by Zerathos** [comment]
I tested it a little and it seems to be related to the length of the shortcut's title. Notepad doesn't cause any text to be cut off, but Ashampoo Burning Studio 2013 does. And yeah, specifically when the window is shrunk to the smallest allowed size.

**Comment by KIDINK** [comment]
![default](https://cloud.githubusercontent.com/assets/1337953/7325751/3aa3da98-eac9-11e4-96a0-7c71984f015e.PNG)

heh

**Comment by FlaminSarge** [comment]
So then only when it hits 3 lines of text, I guess.

**Comment by FlaminSarge** [comment]
Oh, go figure, it DOES expand, just still cuts off the very bottom line. Well, anyways, this commit will handle most cases, though as you can see, it won't handle all of them:
http://i.imgur.com/q4vbMyh.png
