### ISSUE TITLE
Game title as a column when activating new game

### ISSUE THREAD

**Issue by alvr** [DirtDiglett/Pressure-for-Steam#311]
The background of the game title is a column header. Yo can click and when hover the background changes.

![2015-04-23 23_32_02-activacion de producto](https://cloud.githubusercontent.com/assets/217315/7323016/19cd7170-eaac-11e4-8ce7-59a0c292ad6a.png)

**Comment by Js41637** [comment]
Ahh yeah I believe this was due to setting a minimum height for column header and in this instance column header isn't needed so it needs to be manually set to `minimum-height=0`
