### ISSUE TITLE
Find DLC Misaligned

### ISSUE THREAD

**Issue by CorruptComputer** [DirtDiglett/Pressure-for-Steam#314]
http://i.gyazo.com/e5411e62126e5832dabe1128b94e4a10.png

**Comment by Zerathos** [comment]
It took me a second to figure out how to replicate this. It happens specifically when the window is shrunk small enough to hide the image that normally accompanies the DLC listing in the Library view. As soon as it's gone, the the store link jumps up.

And it might just be me, but the positioning of that link normally does seem a bit too far down. Here's what it looks like normally:
![](http://i.imgur.com/pbYvbUU.png)

Compared to what a similar link looks like:
![](http://i.imgur.com/amDjVYo.png)
