### ISSUE TITLE
Overlay background looks weird

### ISSUE THREAD

**Issue by Epic47** [DirtDiglett/Pressure-for-Steam#315]
The background on the steam overlay is tiling the same image, you can clearly see the edges. I'm guessing this is not intentional? If it is, then just ignore this I guess.

Here's an example of what I mean http://i.imgur.com/g6JxHIl.png. It's visible towards the bottom right of the screen. My resolution is 2560x1440 by the way.

**Comment by CorruptComputer** [comment]
It is because your resolution is so high, there is no way to make it never tile. Because even if he makes the image larger, some people have different aspect ratios than the normal 16:9.

**Comment by DirtDiglett** [comment]
Oops! I forgot to scale the image instead of tile it... I've fixed it up now :+1:
