### ISSUE TITLE
Achievements Don't Show Up

### ISSUE THREAD

**Issue by CorruptComputer** [DirtDiglett/Pressure-for-Steam#318]
http://i.gyazo.com/574f704b7a1c9c97bc8a09ace2020226.png

I have looked at 4 different games and they aren't loading for any of them. Commit b39dbd40ece77f5f08e393ccb342c4bc86366d91

**Comment by alvr** [comment]
It also happens on the default skin, so I guess is a bug. At least a week ago when I noticed.

**Comment by CorruptComputer** [comment]
Ah, well if this is a steam bug I'll go ahead and close it.
