### ISSUE TITLE
Missing overlay buttons

### ISSUE THREAD

**Issue by KIDINK** [DirtDiglett/Pressure-for-Steam#319]
For example, that big close button.
![qip shot - screen 005](https://cloud.githubusercontent.com/assets/1337953/7395898/e348df6a-eea5-11e4-8322-e814e93238a9.png)

Also steam browser wont load any pages most of times, but this is steam beta only bug. Broken since 'Web Component Update'

**Comment by BarclayTech** [comment]
Literally about to report this.

was in a game and just realised they're missing.

**Comment by CorruptComputer** [comment]
You can close the browser by clicking the little x on the tab until this is fixed.

**Comment by DirtDiglett** [comment]
Ha! That's odd and unexpected. It should be inheriting the buttons from the same file that the chat window does. I'll fix it up when I get home from work. :+1:
