### ISSUE TITLE
Buttons overlap on login page

### ISSUE THREAD

**Issue by CorruptComputer** [DirtDiglett/Pressure-for-Steam#320]
http://i.gyazo.com/2c33cd59fddf8a62990cdd6aef7af5f8.png

Look at the exit and minimize buttons. Commit b39dbd40ece77f5f08e393ccb342c4bc86366d91

**Comment by DirtDiglett** [comment]
Well that's not meant to happen :disappointed: 

I'll fix it up when I get home from work.
