### ISSUE TITLE
Steam Startup page looks really strange

### ISSUE THREAD

**Issue by CorruptComputer** [DirtDiglett/Pressure-for-Steam#321]
http://i.gyazo.com/f52207924390cff8380ab1e369ae5fc2.png

There is a lot of space at the top and the style looks different from everything else. Commit b39dbd40ece77f5f08e393ccb342c4bc86366d91

**Comment by KIDINK** [comment]
buttons are also broken

**Comment by CorruptComputer** [comment]
@KIDINK They seem to work for me.

**Comment by DirtDiglett** [comment]
There's an image that is meant to go there but I made it invisible to fix an awkward bug elsewhere, looks like I forgot entirely about the sign up dialog! I'll have a fiddle with this when I get home from work and make it all pretty and stuff.
