### ISSUE TITLE
"I Agree" button is too long

### ISSUE THREAD

**Issue by CorruptComputer** [DirtDiglett/Pressure-for-Steam#322]
http://i.gyazo.com/4b0c32863ae55ad36a1e7bb688149e8a.png

It looks like it could be shortened a little bit. Commit b39dbd40ece77f5f08e393ccb342c4bc86366d91

**Comment by DirtDiglett** [comment]
This is intended behaviour. Most buttons in the skin have a minimum width and padding applied because smaller buttons are harder to click.

**Comment by CorruptComputer** [comment]
Is there at least a way you could center the text in the button?

**Comment by DirtDiglett** [comment]
Unfortunately not, the only way to center any text is in the controls, which are readonly to skins.

**Comment by CorruptComputer** [comment]
Ok, well thanks.  I would actually like to contribute to this, if I add you on steam would you mind talking that way?
