### ISSUE TITLE
Activity page broken, seemingly at random.

### ISSUE THREAD

**Issue by techNeffect** [DirtDiglett/Pressure-for-Steam#326]
OK, so hi again. I wanted to make sure this was happening more than a few times. It has actually happened with a really old version (well before config.ini was a thing) up to the latest I grabbed last night.

In a nutshell: when you click activity, under your user name, sometimes it only shows scrollbars in the top left, and nothing else. I've uploaded a pic here: http://i.imgur.com/Z1y9u1v.jpg

Most of the time I can click on library or something else, and then click on activity and it'll be back to normal. And this might not be be readily apparent — as I said it happens at random — sometimes right away, sometimes after hours of uptime.

Thanks for the attention, and apologies if it has been posted under something I didn't search for.

**Comment by DirtDiglett** [comment]
Hi @techNeffect, thanks for the report. Unfortunately this is a known Valve bug that occured during their transition to an updated version of chromium. It's not something that can be fixed in the skin it's a matter of waiting for Valve to fix it in the beta releases.
