### ISSUE TITLE
Streaming menu in wrong position on mouseover

### ISSUE THREAD

**Issue by WindFox** [DirtDiglett/Pressure-for-Steam#327]
When in home streaming is enabled, the little down arrow for the menu gets duplicated and put to the right when the pointer is over it.
![clipboard-20150430](https://cloud.githubusercontent.com/assets/3812388/7417996/4518f148-ef38-11e4-9a82-5e0c305765d6.png)

**Comment by DirtDiglett** [comment]
This commit should hopefully fix this. I'm not in a position to be able to test it at the moment, so let me know if it's still happening (Preferably with a screenshot showing how it looks now) and i'll reopen this if it still occurs.
