### ISSUE TITLE
Artists page play traks button

### ISSUE THREAD

**Issue by GOGO98901** [DirtDiglett/Pressure-for-Steam#328]
In the music page under library and then artists
this happens

![artists](https://cloud.githubusercontent.com/assets/2751799/7418282/9f44c1b6-ef64-11e4-9a00-a522b020286d.png)

However on diffrent artists rather than the button saying "play tracks" it says "Play Album" and the button goes under the artwork

![artists2](https://cloud.githubusercontent.com/assets/2751799/7418329/0673d494-ef65-11e4-91b3-4457f7fd3c8c.png)

**Comment by KIDINK** [comment]
I can confirm that.
![default](https://cloud.githubusercontent.com/assets/1337953/7418331/cef6c042-ef75-11e4-9608-90e031257caf.PNG)
