### ISSUE TITLE
Retina Images?

### ISSUE THREAD

**Issue by sebj** [DirtDiglett/Pressure-for-Steam#329]
I have a feeling this is a 'Valve-problem', but is it possible to supply Retina images for Steam skins? Things like the traffic lights, back/forward buttons and various other icons are blurry/slightly pixellated otherwise.

**Comment by DirtDiglett** [comment]
Unfortunately not, I'd love to do it but doing so would also make it work terribly to any non-retina Mac users. Valve only has the option to specify styles for $WINDOWS, $OSX or $LINUX, there is no $OSX-RETINA :-1:
