### ISSUE TITLE
Bug when used certain mod injector (GemFX)

### ISSUE THREAD

**Issue by krakerz** [DirtDiglett/Pressure-for-Steam#331]
Pic (overlay opened in-game) : http://puu.sh/hxYdS.jpg

it's happens when i play some games with some injector, this time is in DOA 5 : LR + GemFX

I'm trying using a mod from, http://www.neogaf.com/forum/showthread.php?t=1023130
GemFX link : http://www.mediafire.com/download/dcvp2q5cqpcbi2u/GEMFXv1_0_8.exe

**Comment by Zerathos** [comment]
Does the same thing happen using the default Steam skin?

**Comment by krakerz** [comment]
yup, kinda but not as bad as the pressure gets
http://puu.sh/hy2eV.jpg (still manage to read most of the font in here)

can't read some font in pressure especially right beside the clock xD

**Comment by DirtDiglett** [comment]
This is not going to be 'fixed'. You're using an external program that I have no control of. As seen in your second screenshot it manipulates the overlay dramatically and causes multiple issues.

There is literally nothing I could do with a Steam Skin to fix something another non-steam program breaks.
