### ISSUE TITLE
Shadows cuts off in About Steam menu

### ISSUE THREAD

**Issue by KIDINK** [DirtDiglett/Pressure-for-Steam#332]
![default](https://cloud.githubusercontent.com/assets/1337953/7440933/dbe05a48-f0d8-11e4-9ec1-3741a01f410f.PNG)
![default](https://cloud.githubusercontent.com/assets/1337953/7440937/02432d3c-f0d9-11e4-9456-05b66122be2c.PNG)

**Comment by FlaminSarge** [comment]
Please point out any other instances of this happening. I know it happens on Overlay somewhere (but I can't remember where), and the fix is quite simple, but we just need to catch it everywhere (Pressure uses outerglow somewhat frequently, I think).
