### ISSUE TITLE
Asian font sizes

### ISSUE THREAD

**Issue by Andify** [DirtDiglett/Pressure-for-Steam#333]
As seen in the screenshots, the font size is too large when using the client in Japanese or simply using Japanese nicknames. Same goes for Chinese and Korean. Would be neat if support for these languages were a possibility.

It's possible that this is an OS X-only issue, I haven't been able to test this under Windows yet.

![screen shot 2015-05-02 at 1 33 11 pm](https://cloud.githubusercontent.com/assets/4118371/7440920/013ae29e-f0d0-11e4-8926-cec144a0b2e2.png)

![screen shot 2015-05-02 at 1 29 10 pm](https://cloud.githubusercontent.com/assets/4118371/7440917/7381ce2c-f0cf-11e4-8700-d1b9cbb4c79b.png)

**Comment by Js41637** [comment]
Only way to fix this would to be an option in the config.ini for different languages that changes their size.

**Comment by talexand** [comment]
Identical issue under Linux. @Js41637 is the fix you suggest possible? 

If not, another option would be patching the font to include glyphs for one or more East Asian languages.

**Comment by FlaminSarge** [comment]
This is only for the text at the top of the main window, correct?
Bebas Neue (the font used up there) doesn't have glyphs for Japanese (http://www.fontsquirrel.com/fonts/bebas-NEUE#characters)

However, Noto, the font used for all the other text, DOES have glyphs forthose, so all other text should work fine.

We could look into alternative fonts that have those glyphs available...

**Comment by Js41637** [comment]
@talexand not exactly like the linux issue because they can be fixed without requiring a config.ini. In order to adjust font and font-size for a certain language it would need to be in the settings file to include an optional config like //include/languages/japan.style and as FlaminSarge said, only the header needs to be changed to be a smaller font-size and use Noto but from what I could tell from FlaminSarge's link, the normal version of Noto doesn't support Japan, Korean or Chinese and require different versions listed on that page. Unfortunately the normal header font (Bebas) does not support those glyphs and I don't think there is any version that does.

**Comment by zhugexiaobo** [comment]
Same issue with Chinese. It's not just the header part but all Chinese fonts are way bigger and lower than english fonts.
Can we chose font by ourselves?

**Comment by FlaminSarge** [comment]
Again, please install Noto Sans CJK from the page I linked before and tell me if the font sizes for everything except the top of the main window remain an issue.

**Comment by talexand** [comment]
Installed to my local fonts directory and updated the cache, then restarted Steam:

![pressureskin](https://cloud.githubusercontent.com/assets/5308179/7462747/a417de42-f24f-11e4-9a69-8159501124c2.png)

**Comment by FlaminSarge** [comment]
So now only the Big text font sizes are incorrect? Can you show us a screenshot of the "Friends" section for a game in its entirety?

**Comment by talexand** [comment]
Actually, the other font sizes were all correct, but unchanged from the original skin. I'll follow up with a bigger screenshot later, but I believe that it's just falling back to the window manager default UI font or the Steam default (Arial?).

**Comment by FlaminSarge** [comment]
It shouldn't be doing that, though. It should be falling back to Noto Sans CJK if you've got it installed (keep in mind there are four different Noto Sans CJK packs: JP, KR, SC, TC; one for each language).

If you've already installed your language's font, that's okay, but if you haven't yet, try this, which includes all 36 of the various styles of Noto Sans CJK:
http://www.google.com/get/noto/pkgs/NotoSansCJK.ttc.zip

It comes from this page:
https://www.google.com/get/noto/cjk.html

**Comment by zhugexiaobo** [comment]
![image](https://cloud.githubusercontent.com/assets/2577087/7496707/6762ef46-f448-11e4-8e38-c6a76126c1be.png)

I use `Noto Sans CJK SC Medium`, looks better. But still some problems.

**Comment by talexand** [comment]
Installing the complete Noto Sans CJK font pack and changing the two referenced files fixed the issue of font fallback for normal size text fonts--now Noto fonts are being used. That leaves just the Bebas Neue font as far as I can see.

**Comment by FlaminSarge** [comment]
Then it's probably best to add something for things like this to the config, I guess.

**Comment by talexand** [comment]
Yup, I changed it to "Noto Sans CJK" in the linked files as you suggested.

**Comment by zhugexiaobo** [comment]
![image](https://cloud.githubusercontent.com/assets/2577087/7509878/bac213f8-f4c8-11e4-9101-f1596a3b43be.png)

Changed to `Noto Sans CJK`.

**Comment by FlaminSarge** [comment]
@zhugexiaobo Did you properly install the fonts? The text saying "You have 7 friends who play The Binding of Isaac" is still styled as the OSX default font, where it should be entirely Noto...

@talexand got a screenshot for him of what it's supposed to look like?

**Comment by talexand** [comment]
Here's a screenshot (JPN):
![steamscr](https://cloud.githubusercontent.com/assets/5308179/7524238/44070358-f49c-11e4-9774-2f5cfc55f91d.png)

**Comment by FlaminSarge** [comment]
@talexand What happens if you change the line in steamscheme.res back to "Noto Sans"?
I'm trying to figure out which file affects which lines.

**Comment by talexand** [comment]
Nothing, I think:

![steamscr](https://cloud.githubusercontent.com/assets/5308179/7549068/e54d4bb0-f5c2-11e4-9ba7-f4a8e6bb7b76.png)

**Comment by FlaminSarge** [comment]
Hmm.... I'll see about making an easy way to handle this, then.

**Comment by DirtDiglett** [comment]
Every font size will need to be tweaked specifically for asian fonts so this isn't going to be quickly fixed but is on the to-do list.
