### ISSUE TITLE
Servers cog to small

### ISSUE THREAD

**Issue by GOGO98901** [DirtDiglett/Pressure-for-Steam#334]
On the servers page I noticed this
![cog](https://cloud.githubusercontent.com/assets/2751799/7441789/6a1934fe-f0ef-11e4-9d5c-d967bce2da87.png)

**Comment by KIDINK** [comment]
I can confirm that
![default](https://cloud.githubusercontent.com/assets/1337953/7441807/9f0a50c4-f100-11e4-89ba-014c01d4a603.PNG)
