### ISSUE TITLE
Various alignment and visibility issues

### ISSUE THREAD

**Issue by bykidi** [DirtDiglett/Pressure-for-Steam#340]
By some reason, highlighted current chosen track is extremely unreadable
![default](https://cloud.githubusercontent.com/assets/1337953/7452095/7785611c-f261-11e4-87d9-372218bf24a0.PNG)

**Comment by KIDINK** [comment]
Pay attention to active & non-active search bar of music player in game overlay
![default](https://cloud.githubusercontent.com/assets/1337953/7452045/f2f9bd58-f260-11e4-802f-15adde1f6eab.PNG)
![default](https://cloud.githubusercontent.com/assets/1337953/7452053/0f398688-f261-11e4-9a21-ff5966290ef3.PNG)

**Comment by KIDINK** [comment]
By some reason, highlighted current chosen track is extremely unreadable
![default](https://cloud.githubusercontent.com/assets/1337953/7452095/7785611c-f261-11e4-87d9-372218bf24a0.PNG)

**Comment by KIDINK** [comment]
Wrong font and text position.
![default](https://cloud.githubusercontent.com/assets/1337953/7452110/daf02a48-f261-11e4-8c06-26b117e9e84c.PNG)

**Comment by FlaminSarge** [comment]
I'd suggest changing the bug title to "Various alignment and visibility issues"
Polish, after all, is a language.

**Comment by KIDINK** [comment]
1. Yes, top of .tga cuts off.
2. Non-active search icon doubles
3. Hard to read highlighted track
4. Comparing to 'Screenshot Uploader' or other title, 'Music Library' title is different position (lowered) and different font

**Comment by bykidi** [comment]
bump

**Comment by Js41637** [comment]
You don't need to bump issues on Github lol.

**Comment by FlaminSarge** [comment]
Cripes, man, I already said I'm working on this, and that I have most of it done. Be patient.

**Comment by DirtDiglett** [comment]
@bykidi please be respectful of us. We are putting our time and energy into this skin so there is no need to act like we're doing nothing or that you need to shove this in our faces by 'bumping' the issue on Git. Issues on Git do not need bumping they are resolved as we fix them and closed.
@FlaminSarge has already said he is working on this issue so it will be fixed when it's fixed, bumping it won't speed that process up... Besides, these are all minor visual issues so aren't critical.

**Comment by FlaminSarge** [comment]
@bydiki I've fixed 1, 2, and 4 of that list of issues you've identified.
Next time, please submit a separate bug for each issue so that we can track and fix each one individually instead of lumping them together. Since I haven't changed the visibility of the highlighted track items, submit a new bug for those.
