### ISSUE TITLE
Translation to other languages

### ISSUE THREAD

**Issue by BanCrash** [DirtDiglett/Pressure-for-Steam#344]
Hi, I think that the only option added by this skin is "Add funds to Steam Wallet", so translate it to other languages shouldn't be difficult. I would translate this text to Spanish if I knew what file I have to edit.

**Comment by alvr** [comment]
Pressure uses the [Steam Translation Server](https://translation.steampowered.com/), but unfortunately this phrase isn't there, so @DirtDiglett added it manually. You can edit [this line](https://github.com/DirtDiglett/Pressure-for-Steam/blob/master/resource/menus/steam.menu#L77) to translate it.

**Comment by FlaminSarge** [comment]
I'd suggest changing it to "#Overlay_MicroTxnAuth_AddFunds" instead, and for Mac OSX there's a few other untranslated lines in the same file.
