### ISSUE TITLE
Downloads Page Visual Bug

### ISSUE THREAD

**Issue by WildManiac** [DirtDiglett/Pressure-for-Steam#345]
Basically, if there are enough items on the downloads page (in my case 4) and you scroll down, the top part will be overlapped by the download summary section. What is not suppose to happen is that some text still shows behind the summary panel.

Pic:
![downloads page bug](https://cloud.githubusercontent.com/assets/11233971/7464770/e48b501e-f293-11e4-9c04-dec51dca1377.png)

**Comment by DirtDiglett** [comment]
This was just fixed in commit 5f4092d6beb5bfe344a224c1ac138a3c4df3f729

Closing.

**Comment by FlaminSarge** [comment]
Remains unfixed after 5f4092d
Same commit introduced an additional bug where the entirety of the download graph is black.

...Will attempt rework.
