### ISSUE TITLE
Glitched emoticons when the chat window is too small.

### ISSUE THREAD

**Issue by s0r00t** [DirtDiglett/Pressure-for-Steam#349]
This is what it normally looks like :
![Normal view](https://i.imgur.com/lZ0TAq8.png)
This is what it looks like when the window is too small :
![Glitched view](http://i.imgur.com/CUepnQy.png)  
As you can see, the chat stays gray, and a (0) is appended to every username.

**Comment by Js41637** [comment]
Are you sure this is a Pressure related issue? Could you try this using the default Steam skin?

**Comment by DirtDiglett** [comment]
I can't reproduce this in the slightest, I've spammed emoticons to people and made the chat window as small and as large as possible and neither causes the issue to reproduce.

**Comment by s0r00t** [comment]
I'm on Ubuntu 14.10, x64. Steam Beta.
I'll try to run without skin, and it seems there's a new version of the steam package.

**Comment by Zerathos** [comment]
Could it be specific to certain emoticons? Try omitting the two where it breaks, csgoglobe and whatever is immediately before it. Also, who sent the message, you or the other person?

**Comment by FlaminSarge** [comment]
I've noticed that you have many, many more unique emoticons than anybody else that's tried testing this.

It's possible that that's the issue, and it would probably happen with default Steam, then, too.

**Comment by Js41637** [comment]
I have like 100 emoticons and never had this issue when I spam people... not that I do or anything... for testing, you know..

**Comment by Js41637** [comment]
Ok just managed to do this. It happens in normal steam as well. Seems there is a certain width that it just doesn't like and renders text.

**Comment by FlaminSarge** [comment]
:steam_locomotive: :beetle:

**Comment by DirtDiglett** [comment]
So based on Js41637 this appears to be a default Steam bug, so if you can report it over on the Beta Steam forums: https://steamcommunity.com/groups/SteamClientBeta/discussions/0/

**Comment by s0r00t** [comment]
Ok, thanks.
