### ISSUE TITLE
Weird shadow in back and forward buttons.

### ISSUE THREAD

**Issue by Jylhis** [DirtDiglett/Pressure-for-Steam#355]
![steam-pressure-back](https://cloud.githubusercontent.com/assets/2924267/7631882/5ae700be-fa50-11e4-84e2-b45151d45c93.png)
I'm using Ubuntu.

**Comment by J5lx** [comment]
Same here.

**Comment by FlaminSarge** [comment]
In which Steam windows this occur? I'm assuming it's because the text gets hidden on these buttons but it didn't disable the outerglow for them.

**Comment by DirtDiglett** [comment]
FlaminSarge has it right, it looks to be a bug with the linux version attempting to apply outerglows to non-existent text.

I'll fix it up shortly.
