### ISSUE TITLE
"+ Add A Game..." Button Missing From Library

### ISSUE THREAD

**Issue by kdstudios** [DirtDiglett/Pressure-for-Steam#356]
On the bottom left of the Library should be a button that says "+ Add A Game..."
As seen in the left image: http://ns1.onteh.net.au/pressureskin/game-details.png
I know you can click the Steam icon at the top and then click add a game but that is one extra click I've never had to do before and is literally getting on my nerves because I buy a LOT of bundles that give me Steam keys.

If this was something that you considered unnecessary, I urge you to please reconsider.
Or perhaps provide an option to turn it back on in the config?
Or perhaps tell us unsavvy skin editors how to re-add it ourselves?
Thanks.

This is without doubt the most beautiful, best looking and a real joy to use skin I've used so far. 
But this one thing is seriously making me consider using others, I'm not really using this as a threat because it really doesn't matter if I use your skin or not, heh. I'm just one guy. You can call me lazy, I don't care. I just prefer to spend my time gaming a little more than that extra millisecond/second it takes to click the steam button and then add a game when I could quite simply just click  "+ Add A Game..."

**Comment by Zerathos** [comment]
It was removed intentionally, see #78.

**Comment by kdstudios** [comment]
Well... To quote Cr0ssfire:

"cr0ssfire commented on 10 Nov 2014
uncool"
