### ISSUE TITLE
Problem with colors in library

### ISSUE THREAD

**Issue by alvr** [DirtDiglett/Pressure-for-Steam#358]
![2015-05-21 20_54_37-steam](https://cloud.githubusercontent.com/assets/217315/7756712/5fe011f2-fffd-11e4-85ba-9c2a2bbde60c.png)
![2015-05-21 20_55_03-steam](https://cloud.githubusercontent.com/assets/217315/7756713/5ff777f2-fffd-11e4-80e6-920ac080afcd.png)
![2015-05-21 20_57_26-steam](https://cloud.githubusercontent.com/assets/217315/7756714/6007f9ce-fffd-11e4-9801-2a88c462c643.png)

Using latest beta version and commit.

**Comment by DirtDiglett** [comment]
I've been a bit absent recently, but i'm back so i'll look into this and get it sorted out ASAP.

**Comment by DirtDiglett** [comment]
Can you please copy-paste the modifications you've done to config.ini, as i'm sure that is the cause of these issues.

**Comment by alvr** [comment]
I didn't make any changes to config.ini, but deleting and copying it again worked.
