### ISSUE TITLE
Text cut off in friend chat window

### ISSUE THREAD

**Issue by fatek** [DirtDiglett/Pressure-for-Steam#359]
Using pressure v1.0.0 on Linux Mint 17

![text-area](https://cloud.githubusercontent.com/assets/12451793/7765096/118f026c-000f-11e5-8251-92b61a351870.png)

**Comment by DirtDiglett** [comment]
Hmm, seems to be a linux-specific issue, I've had some other Linux users mentions it too. I'll look into getting it sorted out asap.
