### ISSUE TITLE
Restart Steam button

### ISSUE THREAD

**Issue by CorruptComputer** [DirtDiglett/Pressure-for-Steam#360]
Would it be possible to add a restart steam button? Rather than having to wait for it to close then open it again.

**Comment by Zerathos** [comment]
There is one.

**Comment by CorruptComputer** [comment]
On the right click menu?

**Comment by Zerathos** [comment]
Oh, there. I'm pretty sure that's not possible. Go to Settings > Interface > Set Taskbar Preferences and you'll see the full list of what Steam allows in that menu, and Restart Steam isn't in there.

**Comment by CorruptComputer** [comment]
Oh, well I had just saw that the menu was stylized and thought it could be added. But if its not possible ill just close this.
