### ISSUE TITLE
Choose a License

### ISSUE THREAD

**Issue by J5lx** [DirtDiglett/Pressure-for-Steam#361]
Currently I'm thinking about making a version of Pressure for a piece of software called [Elementary](https://www.enlightenment.org/about-efl). It it similar to Valve’s VGUI, but it is freely available as Open Source and can be used by other programs to create UIs; therefore a skin (or theme, how Elm calls it) for it allows for changing the looks of all programs using it. However I noticed that Pressure is not licensed in any way at the moment, and [as GitHub puts it](https://github.com/blog/1964-open-source-license-usage-on-github-com): “Unless you've explicitly told others that they can modify and reuse your work, you've only showed others your code; you haven't shared it.” (This also affects other content which is not code, even though they don’t mention it.) Effectively this makes it impossible to (legally) share any Pressure-based skins or themes which I or others may create. Since you already made this project quite “open” by putting it here on GitHub and accepting contributions from others, I suggest you choose a license for it so it is clear what others are allowed to do with it (or not). If you decide to use an open license model (which I’m hoping for), I’d recommend to use a [Creative Commons license](https://creativecommons.org/choose/) for media (like images) and [a specialised Open Source license](http://choosealicense.com/licenses/) for the code, like the game [0 A.D. does it](https://github.com/0ad/0ad/blob/master/LICENSE.txt).

Final note: If you want to allow other people to create something based on Pressure (like an Elementary theme), you should make sure that the Creative Commons license doesn’t include the ND/NoDerivatives “module” and that the code license has “Modification” listed in the “Permitted” column on choosealicense.com.

**Comment by CorruptComputer** [comment]
AGPLv3 is a good license, it corrects a loophole in GPLv3 that allows people to go closed source with an open source project. its what we are now using at https://github.com/tgstation/-tg-station because people were running off with our code and making others pay to play. Not saying that will happen here, but its best to be safe.

**Comment by J5lx** [comment]
Are you referring to the Tivoization issue [Linus Torvalds is so upset about](https://www.youtube.com/watch?v=PaKIZ7gJlRU)? In that case one could also just use the GPLv2 (without the “or later” clause), like Linux does.

Oh, and I forgot: Please avoid any Licenses that try to put the code into the Public Domain (like the Unlicense). I like what they are trying to do, but the problem is that simply “putting things into the Public Domain” is just not possible in many countries (like Germany, where I’m living). Therefore “unlicensed” or similar code cannot be used in such countries, which is completely against anything such licenses stand for in the first place. See e.g. <http://programmers.stackexchange.com/a/147120> (There are better articles about the topic written by actual lawyers, but I can’t find them atm since I lost my browser history recently).

**Comment by DirtDiglett** [comment]
Thanks for actually caring about licensing and ensuring correct permission is given before just using Pressure and its assets, I really respect that.

I'll sort out an appropriate license tonight when I get home from work :+1:

**Comment by DirtDiglett** [comment]
OK, so i'm having a bit of trouble deciding on a license. I am happy for people to modify the code, repurpose it, etc. but not for commercial use or to sell derivatives, but all the licenses I find seem to permit this. 

In this case though, J5lx, you've got my express permission to build your elementary skin based off Pressure as long as you don't earn money from it :+1:

**Comment by CorruptComputer** [comment]
I don't believe AGPLv3 allows people to take your code and sell it. It also expressly states that you must be open source, so someone can't take your skin and keep you from knowing.

**Comment by benblank** [comment]
I am very much not a lawyer, but I'm pretty sure the AGPL (any version) doesn't prohibit monetization.  For example, [section 4](https://gnu.org/licenses/agpl.html#section4) ends with:

> You may charge any price or no price for each copy that you convey, and you may offer support or warranty protection for a fee.

If you want to prevent derivative works from being sold, you might consider a [Creative Commons](http://creativecommons.org/choose/) license instead.  They're specifically designed to apply to non-compiled materials and optionally allow you to forbid commercial use.

**Comment by J5lx** [comment]
@DirtDiglett Okay, thanks for the permission. In fact it seems like [there are actually no OSS licenses prohibiting selling](http://programmers.stackexchange.com/a/69093) :/. Maybe a suitable solution would be some custom notice in the license but, well, [IANAL](https://en.wikipedia.org/wiki/IANAL).
@benblank The problem is that the Creative Commons licenses are not made for code. [Even the official CC wiki recommends against using it for code](https://wiki.creativecommons.org/Frequently_Asked_Questions#Can_I_apply_a_Creative_Commons_license_to_software.3F).

**Comment by J5lx** [comment]
On a second thought though: The CC wiki is exactly about software (not specifically code), so one could also see Pressure's code as some kind of "art in code form" and happily apply a CC license. Just saying.

**Comment by DirtDiglett** [comment]
Licensing is so damn confusing and tricky, I don't like it one bit!

**Comment by J5lx** [comment]
I know what you mean... I switched my preferred (code) license many times myself until I found one that I *really* liked (MPL). Take your time and choose something you feel comfortable with.

**Comment by TheLonerD** [comment]
https://tldrlegal.com/
A little help with various licenses.

**Comment by sebie** [comment]
As this hasn't been mentioned yet, although @TheLonerD 's suggestion is good; is GitHub's [choosealicense.com/](http://choosealicense.com). Good luck!

**Comment by DirtDiglett** [comment]
I've decided to go with "Creative Commons Attribution NonCommercial (CC-BY-NC)" since it seems to tick all the boxes I think.

I'll pop a LICENSE.txt into the project asap.

**Comment by J5lx** [comment]
Cool - Great to see that you found one that works for you!
