### ISSUE TITLE
Euro sign overlaps with wallet amount

### ISSUE THREAD

**Issue by jblomme** [DirtDiglett/Pressure-for-Steam#366]
![pressure](https://cloud.githubusercontent.com/assets/4263675/7901501/45cb6164-078b-11e5-978d-b5ff5f11ecad.PNG)
The spacing between the credit amount and currency denominator is too small, causing its shadow effect to overlap. A minor flaw in an otherwise great product!

**Comment by DirtDiglett** [comment]
And how does it look on normal Steam? I don't have euro as my currency, so I cannot test it myself but everywhere else I put "100€" it shows fine, with the same font choice, same size, etc.

**Comment by jblomme** [comment]
![default](https://cloud.githubusercontent.com/assets/4263675/7908678/349a627a-0847-11e5-8353-a07fb45c4067.PNG)
There is no space between the amount and the Euro sign. This is probably why the shadow overlaps. I'm guessing the amount and symbol are two different objects and hence layers, with the symbol being on top?

![format](https://cloud.githubusercontent.com/assets/4263675/7908734/8d38d52e-0847-11e5-8043-a3477649a47f.PNG)
It does not appear that Windows-settings affect this notation. Here, it is currently set to the Dutch standard. This means that the currency sign should be before the amount, which it is not in Steam.

**Comment by DirtDiglett** [comment]
I've been looking into this and unfortunately it's not something I can fix other than outright removing the glow altogether which I don't want to do. If you look at the default Steam screenshot you'll hopefully notice that the euro symbol is using a font size 1pt larger than the actual value - same goes for the Pressure one too, and it's not added as part of the value string, it's a separate element which puts it on a higher z index causing the shadow... It should be added to the same string as the value which would eliminate the problem but that's something outside of a skin's control.

I'm sorry :disappointed:

**Comment by jblomme** [comment]
That's unfortunate. Thanks anyway for your efforts, keep up the good work!
