### ISSUE TITLE
Find On Page string does not stay in field

### ISSUE THREAD

**Issue by GOGO98901** [DirtDiglett/Pressure-for-Steam#367]
The text field goes over the image and further
![findonpage](https://cloud.githubusercontent.com/assets/2751799/7902871/7f4647b2-07c0-11e5-90fd-6befa93e1b4d.png)

**Comment by FlaminSarge** [comment]
In which windows does this occur? Overlay, Main Steam, or both?

**Comment by FlaminSarge** [comment]
@DirtDiglett I've seen inset-left=0 fix a lot of the search bar issues, so maybe that should be global? Was there a place it didn't work out?

**Comment by GOGO98901** [comment]
I have only tested this in the main steam web pages

**Comment by FlaminSarge** [comment]
I think I've got it covered. We'll see how it turns out.
