### ISSUE TITLE
Request for some assistance with moving the Installed and Search buttons to the left side. 

### ISSUE THREAD

**Issue by Wiggin38** [DirtDiglett/Pressure-for-Steam#369]
Hi before the official release I was able to get the skin to look the way I want with some help from someone on here. Since then I can't figure out how to fix what I want to fix. 

Original: http://imgur.com/gSgFfBG

What I want: http://imgur.com/PMhIFdp

Hopefully this is possible without breaking other elements. If not that's fine too. 

Thanks for the awesome skin!

- Wiggin

**Comment by FlaminSarge** [comment]
It would help if you could identify/present information about the unicode symbol present in your steam nickname.

**Comment by Wiggin38** [comment]
Oh I have given up on fixing that. I have the same issue in stock steam so I assumed it was un-fixable. 

Just in case though Wiggin ✿ that's my name with the "flower". 

What I really want to do is move the Installed and Search over to be on the left side without breaking the music.

**Comment by FlaminSarge** [comment]
Your bug description doesn't at all indicate that, and the bug title is... well, pretty useless, unfortunately.

**Comment by FlaminSarge** [comment]
What about grid view? Grid view adds the zoom bar, and how does that fit into the mockup you've got?

**Comment by Wiggin38** [comment]
What would I change in the uinavigatorpanel to move the search and install drop down menu over to the left ? 

In previous attempts in previous builds when I would move the Install drop down over and switch to music the grid view icon would overlap with the music drop down.

**Comment by DirtDiglett** [comment]
Short answer is it's not a simple change as it'll involve either overlapping some elements (Like the zoom slider) or a rework to move those elements elsewhere.

I'm considering making a replacement layout files to use to switch between a left-aligned and default method (It can't be done with a config.ini).

**Comment by Wiggin38** [comment]
Thanks DirtDiglett for the response. I was starting to think that after messing around with like every setting in the config.ini files. I would very much appreciate a left-aligned option.

**Comment by DirtDiglett** [comment]
This is going to be a tweak in the next release of Pressure, so i'll close this now.

**Comment by Wiggin38** [comment]
Just wanted to say thanks! I look forward to it. Any ETA ? ;)

**Comment by Zerathos** [comment]
[You can do it now.](https://github.com/DirtDiglett/Pressure-for-Steam/commit/66cccbbfe0ada7c5aa00d01b9c5ea7cb0e2b5ec8)

**Comment by Wiggin38** [comment]
When you go to the music section it looks like this. 

http://i.imgur.com/HMVNPEv.png

Did I do something wrong ?

**Comment by Zerathos** [comment]
If it works at all you've done it right. That's just a bug.

**Comment by DirtDiglett** [comment]
Yeah I forgot about the music buttons in the tweaked left-aligned one. I've just fixed it in the latest commit.
