### ISSUE TITLE
Verify email dialog text overlap

### ISSUE THREAD

**Issue by SwooshyCueb** [DirtDiglett/Pressure-for-Steam#371]
![image](https://cloud.githubusercontent.com/assets/1675114/7971621/cb055d9e-0a0b-11e5-8adf-bf6689b3ddc1.png)

I'm using Linux, if that matters. Just pulled from github, so I've got the latest version. I'll keep my email address unverified so I can test fixes, if you need me to.

**Comment by DirtDiglett** [comment]
I've already got a verified email of course, so I'll have to create a new Steam account to test this. I'll fix it soonish.

**Comment by SwooshyCueb** [comment]
My email is still unverified, so I can totally test this for you if you need me to.

**Comment by DirtDiglett** [comment]
Well to save me the hassle, can you run Steam in Dev mode and when in the popup press F6, click on the dialog and screenshot the little popup you'll have for it please.
![image](https://cloud.githubusercontent.com/assets/3527401/8562361/dc48055a-2574-11e5-88e0-fd4478d60a0c.png)

**Comment by SwooshyCueb** [comment]
![image](https://cloud.githubusercontent.com/assets/1675114/8563110/92fbd936-2500-11e5-919c-04242a79b1e8.png)
![image](https://cloud.githubusercontent.com/assets/1675114/8563128/df9872cc-2500-11e5-91c8-02f4aaba3de8.png)
![image](https://cloud.githubusercontent.com/assets/1675114/8563137/f4c0698e-2500-11e5-8b92-705fe13d8cff.png)
![image](https://cloud.githubusercontent.com/assets/1675114/8563139/04bbc356-2501-11e5-8bd2-4129fb718b6b.png)

**Comment by SwooshyCueb** [comment]
In case you need this as well
![image](https://cloud.githubusercontent.com/assets/1675114/8565143/5c3b4716-2518-11e5-92d0-b6be186522e2.png)
(The email update prompt bar is separated from the rest of the header by a few pixels)

![image](https://cloud.githubusercontent.com/assets/1675114/8565075/b6a916de-2517-11e5-9189-86fd8887d6a3.png)
![image](https://cloud.githubusercontent.com/assets/1675114/8565091/cd8892e4-2517-11e5-9bdf-13397ab9f02a.png)
![image](https://cloud.githubusercontent.com/assets/1675114/8565097/e40c233c-2517-11e5-9054-934b2b4dd42f.png)
![image](https://cloud.githubusercontent.com/assets/1675114/8565104/f2e3e822-2517-11e5-8274-dc81ce90aeb9.png)
![image](https://cloud.githubusercontent.com/assets/1675114/8565110/01a7e9bc-2518-11e5-805f-89d37b02fd76.png)
![image](https://cloud.githubusercontent.com/assets/1675114/8565115/1009b508-2518-11e5-9a86-3aa574e14bb1.png)
![image](https://cloud.githubusercontent.com/assets/1675114/8565125/25e89ac4-2518-11e5-9cf5-aacc8c32a173.png)
![image](https://cloud.githubusercontent.com/assets/1675114/8565130/33c91d6c-2518-11e5-90f2-2447b25881ca.png)

**Comment by DirtDiglett** [comment]
Thanks muchly! I'll work on this shortly.

**Comment by DirtDiglett** [comment]
I'm not able to fix this in the current way Pressure is done, it's going to be fixed with Pressure Classic when I do that though.
