### ISSUE TITLE
Incorrect Font sizes under linux

### ISSUE THREAD

**Issue by thatbooisaspy** [DirtDiglett/Pressure-for-Steam#374]
Under linux (arch linux to be exact, but I don't think that matters) using the Pressure skin the titles of games and the tabs are oversized:
http://i.imgur.com/xzh8Fnw.png

![image](http://i.imgur.com/xzh8Fnw.png)

While the skin is still useable, it seems to be an issue with one the fonts, any ideas? I saw that one of the other issues had problems with the navigation font size too.

**Comment by J5lx** [comment]
You need to install the fonts in the "font - INSTALL THESE FIRST" folder first.

**Comment by CorruptComputer** [comment]
^

**Comment by thatbooisaspy** [comment]
I did though?

**Comment by Zerathos** [comment]
Did you follow the directions laid out in the readme when doing so?

**Comment by DirtDiglett** [comment]
Doesn't look like the fonts are installed at all for the headings, it utilizes Bebas which this is clearly not.

I don't know enough about *nix to troubleshoot it, but please follow the instructions provided by another Linux user on how they got it working:

>Linux: If a graphical font viewer is installed on your system you will most likely be able to install the fonts easily using that program. Otherwise you need to “install” the fonts manually by copying them to /usr/share/fonts (to install them system-wide) or ~/.fonts (to install them only for the current user) and executing fc-cache -fv in a terminal.

Ultimately though, this isn't a Pressure issue it's just that you don't have the fonts installed so it defaults to the system-default font. 

Closing.

**Comment by dyskette** [comment]
I had the same issue than OP. And instead of installing the fonts locally in ~/.local/share/fonts, I installed them system-wide in /usr/share/fonts, and that seems to be okay for steam.

I don't know why steam couldn't see local fonts. So, I'm leaving this comment for reference.
