### ISSUE TITLE
Friend List and Chat Visual Glitch

### ISSUE THREAD

**Issue by vsilvar** [DirtDiglett/Pressure-for-Steam#376]
The selected language information overlaps the search bar, and isn't aligned in the chat.

![chat](https://cloud.githubusercontent.com/assets/279175/8149878/72b7043e-12cc-11e5-8c2a-d67debb1b99d.png)
![friend list](https://cloud.githubusercontent.com/assets/279175/8149879/72c387e0-12cc-11e5-8575-86c9f486c8a0.png)

**Comment by Zerathos** [comment]
This can't be fixed, see #224 and #56.

**Comment by vsilvar** [comment]
You can check https://github.com/Elundris/Air-for-Steam
In that skin the gray background is gone, so it should be possible to do something.

**Comment by vsilvar** [comment]
Just went through the files and found that:
TextEntry.IMEBGColor		"0 0 0 0"
TextEntry.IMEFGColor		"white"

Hides the language information, the only problem is that the TextEntryClearButton becomes misaligned. Not sure how to fix that, but it's still an improvement.

**Comment by FlaminSarge** [comment]
Can you guys try the following?:
	TextEntry.IMEBGColor		"225 225 225 0"
	TextEntry.IMEFGColor		"DarkImageOverlay"

**Comment by vsilvar** [comment]
Look good to me

**Comment by DirtDiglett** [comment]
I've added this to the main branch, thank for the help guys. I feel a bit silly because every time I tried to tackle this issue it never occured to me to just search the files for the same RGB color as the background of it... It was staring at me in the face :(
