### ISSUE TITLE
Chat Misalignment

### ISSUE THREAD

**Issue by CorruptComputer** [DirtDiglett/Pressure-for-Steam#383]
http://i.gyazo.com/52f68bb98c530e5872e9f0dfe3223c1f.png

**Comment by DirtDiglett** [comment]
What specifically are you referring to? If it's the gap between the voice chat bar and the user list it's expected behaviour, that is an area one can grab and resize the user list, so if I remove the gap there's  only 1 pixel to be able to grab it.

**Comment by CorruptComputer** [comment]
The chat settings button isn't centered vertically, and it was before. I'm not sure if this was an intended change, but if I was I personally don't like it.

**Comment by FlaminSarge** [comment]
The chat settings text was never centered vertically. 
The position of that element is shared with the position of the text for group info on Steam group chats. If you pull up one of those you'll see that THAT element now mirrors friend chats in positioning. 
Unfortunately it has the side effect of putting the chat settings element in an awkward place for private group chats. 
I'm trying to figure out a good way to go about this, but the end result is that there will always be an awkward amount of space left on chat title panels...

**Comment by DirtDiglett** [comment]
@FlaminSarge pretty much said it all for me.

Closing as it's expected behaviour.
