### ISSUE TITLE
Shared by user text gets cutoff

### ISSUE THREAD

**Issue by Enderwalker97** [DirtDiglett/Pressure-for-Steam#384]
![snapshot2](https://cloud.githubusercontent.com/assets/13104271/8411096/9c68dc2a-1e71-11e5-9123-421f85d24be2.png)

**Comment by Zerathos** [comment]
Are you on the most recent commit? I'm fairly sure that was fixed some time ago.

**Comment by Enderwalker97** [comment]
I'm using ver 1.0.1

**Comment by bykidi** [comment]
@Enderwalker97 redownload it and test again

**Comment by DirtDiglett** [comment]
This'll be because the font sizing on Linux and Mac is different compared to Windows' version.

I actually need some people to be guinea pigs for me while I work on the text sizing, would you like to participate?

**Comment by bykidi** [comment]
What OS's we should test it on?

**Comment by DirtDiglett** [comment]
@bykidi Linux and Mac.
