### ISSUE TITLE
Excessive CPU usage

### ISSUE THREAD

**Issue by ghost** [DirtDiglett/Pressure-for-Steam#387]
When running steam with your skin, steam.exe sits at 25% CPU usage when doing absolutely nothing. I've tried this with different skins, and I've reinstalled steam a couple of times. This only happens when your skin is active, with no - or other skins the CPU usage for steam.exe is at 0% when doing nothing.

I'm running Windows 8.1 64 Bits, an i5 2500k @ 4.7GHz and 16 Gigs of RAM
If I need to provide additional info, please let me know!

(The problem occurs on both the live steam version and the beta update)

**Comment by Zexorz** [comment]
Win8.1 64bits - i7 4510u with 8gb ram doesn't have high CPU load here. (0.4% of cpu)

**Comment by Zerathos** [comment]
Errr...is this with the most recent version of the skin? There was an issue with Library view that could do this (see #100 for more information), but that should have been patched months ago (and it's actually not the only skin to have had a similar bug). What are you doing when you experience this increased CPU usage?

**Comment by bykidi** [comment]
Please test it with latest steam beta version (released yesterday)

**Comment by testman3** [comment]
Thanks for the replies guys, after re-downloading the most recent version of the skin and enabling the steam beta update it seems to be working properly again. The CPU usage was high regardless of which tab I was on, and now it's sitting around 0% again.

**Comment by bykidi** [comment]
switch to offline mode (both offline and invisible), switch to different steam client pages and check cpu load again

and still, i can't reproduce this on my side

**Comment by DirtDiglett** [comment]
Run steam with -dev mode and when the issue occurs go to the console tab and screenshot that for me.

![stamdev](https://cloud.githubusercontent.com/assets/3527401/8513414/de107e4e-23ad-11e5-8216-be6561668ae4.PNG)

**Comment by testman3** [comment]
Hi again, it seems like I'm able to reproduce it now - thanks to the offline tip. If I launch steam to the library view, it immediately goes up to 25% and stays there. If I launch steam to the store page and then switch to library view nothing happens. The moment I start scrolling through my library the usage spikes up to 25% and stays there.

This was the only thing that appeared in the console when usage spiked:

![console](https://cloud.githubusercontent.com/assets/13148325/8518970/1dbf2b64-23cf-11e5-819f-b5034cf9627b.PNG)
I left it running for a while with the high usage, but nothing else appeared in the console

**Comment by Zerathos** [comment]
Alright, I've done some testing on my end. It seems to be related to games that are missing any sort of information, Friends, Achievements, News, etc. @testman3, please try this out and confirm. Here's an example of what I mean:
![](http://i.imgur.com/t9CqTln.png)

My console log was similar to @testman3's:
>\src\public\tier1/interface.h (264) : Assertion Failed: m_pModule
>Failed to init SteamVR because it isn't installed
>ExecCommandLine: ""C:\Program Files (x86)\Steam\steam.exe" -dev"
>System startup time: 102.96 seconds
>Opening joystick XInput Controller
>CAPIJobRequestUserStats - Server response failed 2
>CAPIJobRequestUserStats - Server response failed 2
>CAPIJobRequestUserStats - Server response failed 2
>CAPIJobRequestUserStats - Server response failed 2
>CAPIJobRequestUserStats - Server response failed 2
>CAPIJobRequestUserStats - Server response failed 2
>CAPIJobRequestUserStats - Server response failed 2
>CAPIJobRequestUserStats - Server response failed 2

**Comment by bykidi** [comment]
But still, this is only pressure-related?

**Comment by Zerathos** [comment]
In the default skin it spikes for a split second, then stabilizes. The console output is the same. Only in Pressure does it consistently max out a core and not let go until the view moves to another game or non-Library screen.

**Comment by testman3** [comment]
@Zerathos Yep, it seems that the cpu usage only spikes when I have a game with missing info selected!

![capture](https://cloud.githubusercontent.com/assets/13148325/8529324/75aeabfc-2419-11e5-89a7-d199f7364a37.PNG)

**Comment by DirtDiglett** [comment]
How are you guys forcing these to show no info? I tested Dirt Bomb and it has information. If I go into offline mode to try I can't reproduce the issue. I can see you're in online mode because you have 9 friends online @testman3 

I also can't find Chess the Gathering to try to reproduce it the same way as you, @bykidi 

If you guys can do me a favour though and delete `gamespage_details_welcome.layout` and `gamespage_details_nonsteam.layout` from the skin and restart Steam and try again for me and let me know if that solves the issue.

**Comment by bykidi** [comment]
@DirtDiglett this bug can be also produced by using Custom Added Game, try for youself

**Comment by bykidi** [comment]
Deleting gamespage_details_nonsteam.layout does nothing.

Deleting gamespage_details_welcome.layout fixes CPU load

**Comment by testman3** [comment]
@DirtDiglett I'm not forcing anything to show no info, it just happened when I installed the game. No idea why it's doing that. After deleting dirty bomb and installing it again from the store page, It still shows no info..  The problem also occurs in offline mode - just tried that as well.

Same as @bykidi 

Deleting gamespage_details_welcome.layout    fixes the issue :+1: 
Deleting gamespage_details_nonsteam.layout  does nothing
