### ISSUE TITLE
DLCs in library

### ISSUE THREAD

**Issue by GOGO98901** [DirtDiglett/Pressure-for-Steam#390]
1. Could be just me but when selected the item can be painful to read
2. When scrolling the item clips through the top (like #294)

![dlc](https://cloud.githubusercontent.com/assets/2751799/8543265/9194f676-2493-11e5-8a0f-a852f4929c95.png)

**Comment by bykidi** [comment]
I can confirm the second one
![default](https://cloud.githubusercontent.com/assets/1337953/8547412/51bcc680-24c7-11e5-8995-c78b5ad9428f.PNG)

**Comment by GOGO98901** [comment]
@bykidi sorry for the late reply. I'm using windows 8.1
