### ISSUE TITLE
[Linux Development Branch] Some fonts too small

### ISSUE THREAD

**Issue by id310791** [DirtDiglett/Pressure-for-Steam#391]
Ubuntu 15.04 x64, Steam Beta Client
Screenshots:
![screenshot from 2015-07-07 23 04 14](https://cloud.githubusercontent.com/assets/9195693/8555998/aa5cc026-24fc-11e5-86f4-b4cc1db8e8a8.png)
![screenshot from 2015-07-07 23 05 59](https://cloud.githubusercontent.com/assets/9195693/8556013/c568b94c-24fc-11e5-9ab6-1d8d46804936.png)

**Comment by Andify** [comment]
Getting the same under OS X.
Yosemite 10.10.4, Steam Mac Beta Client

![screen shot 2015-07-07 at 10 15 27 pm](https://cloud.githubusercontent.com/assets/4118371/8556210/d6af401a-24f5-11e5-9142-f498ad798d3f.png)

![screen shot 2015-07-07 at 10 15 46 pm](https://cloud.githubusercontent.com/assets/4118371/8556211/d8ec320c-24f5-11e5-8277-4eb97922fc49.png)

**Comment by Alkaris** [comment]
I have somewhat similar issue, except the fonts are too big, I just manually change the font size in all the styles to my preferred size to fix them. Quick fix I did was to use Terminal to mass edit all the styles and layouts by searching out and replacing `font-size=` in all the files to the sizes I want them to be.

`find . -name "*" | xargs grep -i 'font-size='`

this searches all strings containing in the styles and layouts with `font-size=` which will show the font sizes used for them.

`grep -rl matchstring somedir/ | xargs sed -i 's/string1/string2/g'`

using grep will find the string you want to change then using pipe `|` into `xargs` and `sed` which replaces the string you want to change. For example in the following you'd make it look like this;

`grep -rl font-size=36 . | xargs sed -i 's/font-size=36/font-size=28'`

just change the font size numerical value to whatever you want it to be at.

**Comment by VampiricPie** [comment]
Linux LXLE 12.04.5 Same small text problem.

![text](https://cloud.githubusercontent.com/assets/13597552/9020872/d541f9c6-37eb-11e5-86f2-85c37befc92a.png)

**Comment by DirtDiglett** [comment]
That experimental branch ended up compeltely breaking everything in ways it really shouldn't have. I've since abandoned that branch and will work on properly sorting out the fonts after Pressure² when I do Pressure Classic
