### ISSUE TITLE
Steam File viewer

### ISSUE THREAD

**Issue by GOGO98901** [DirtDiglett/Pressure-for-Steam#393]
The `back one folder` and the `new folder` buttons are both sifted to the right
![image](https://cloud.githubusercontent.com/assets/2751799/8647049/869dd0a4-294c-11e5-8bfa-a6a32efd6512.png)

**Comment by CorruptComputer** [comment]
Also it seems like the lists information could be moved to the right 1 or 2px.

**Comment by bykidi** [comment]
Does Open Cancel buttons are movable too? 1-2px upper, maybe?

**Comment by DirtDiglett** [comment]
I've merged the fixes @Js41637 provided. Let me know how it goes now.

**Comment by GOGO98901** [comment]
![file](https://cloud.githubusercontent.com/assets/2751799/9006541/51e708fc-3780-11e5-988e-dc8709bda6fa.png)
It looks a lot better but I think they are still off center

**Comment by GOGO98901** [comment]
![image](https://cloud.githubusercontent.com/assets/2751799/9021447/61494d68-383a-11e5-9453-38337a60ab05.png)

Thanks for the fixes.
