### ISSUE TITLE
Misalligned Text on Status window

### ISSUE THREAD

**Issue by Heyallo** [DirtDiglett/Pressure-for-Steam#397]
I've just started using the skin and I love it, however I noticed this misalligned text when a friend tried to invite me to play Dungeon Defenders 2 with them

![2015-07-25_00001](https://cloud.githubusercontent.com/assets/2034627/8888007/8b74dfbe-32de-11e5-9075-0568feeecc07.jpg)

**Comment by Js41637** [comment]
Does it do this for other games that don't show game info? I can't replicate this issue.

**Comment by GOGO98901** [comment]
Are you using steam beta? (That could be the problem, maybe)

**Comment by Heyallo** [comment]
I am using the beta (and there has been a few beta updates lately), It has however seemed to stop.
