### ISSUE TITLE
Steam button covering menu (top Left)

### ISSUE THREAD

**Issue by GOGO98901** [DirtDiglett/Pressure-for-Steam#400]
I just noticed this
![top- button](https://cloud.githubusercontent.com/assets/2751799/8943881/1d0b780a-3575-11e5-8f57-c9776667f5d6.png)
when clicked it opens the "install steam vr" page
I can not open the menu that is there

**Comment by GOGO98901** [comment]
This is a new feature as of the new beta update
http://steamcommunity.com/groups/SteamClientBeta#announcements/detail/52141089726085139

**Comment by bykidi** [comment]
Seems fine to me (latest beta + latest skin commit + windows 10 10240 + russian locale)
![default](https://cloud.githubusercontent.com/assets/1337953/8950993/5e54f460-35d1-11e5-89a7-bc08e4ca91ce.PNG)

**Comment by GOGO98901** [comment]
In your screenshot the button seems to be gone completely (maybe you have VR installed?)
I cleaned my skins folder and re downloaded the skin (latest commit) and issue persists
I would also tell you the build number on steam but I cant click the menu. This is the latest beta download however.

**Comment by GOGO98901** [comment]
On my brothers computer I tested it with the latest update and the button was not there. So I changed to default skin and the start VR button was not there.
Therefore I am not sure why it is on my screen. Maybe I have some game that supports VR or something? I'm don't know
Anyway this is an issue anyway

#### What I see on Pixel vision v2:
![image](https://cloud.githubusercontent.com/assets/2751799/8954350/e312cf96-35dc-11e5-9ae8-31331e8ba2fa.png)
#### What I see on default:
![image](https://cloud.githubusercontent.com/assets/2751799/8954360/013f1d08-35dd-11e5-9ebb-0cb7fb811451.png)

Is there anyone who also sees this issue?

**Comment by s0r00t** [comment]
I also have this, French locale, Arch x64, always latest version of the repo.  
You made a mistake on the title, the button is at the top left, not the top right... ;)

**Comment by Alkaris** [comment]
Same issue here on Linux, cleaned and fresh download.
![shutter_2015_07_07-31-15__07_06_56_am](https://cloud.githubusercontent.com/assets/6682988/8995290/d8ad5b66-3753-11e5-97e4-22ba4885f9ab.png)
