### ISSUE TITLE
Textbox bug

### ISSUE THREAD

**Issue by szakigeri** [DirtDiglett/Pressure-for-Steam#406]
Hello!

In the Steam Client/Overlay, let it be the search box or chat, if I type in "ffi", the textbox gets bugged, the cursor moves backward one character and continues writing there. The cursor cannot be moved forward, 'End' command on the keyboard doesn't work, nor 'Ins'. The only fix is to delete everything you've already typed it. I discovered it by trying to type the word 'ruffian' into chat but I could not input it properly cause the textbox didn't let me. This only occurs where the textbox is in the UI, the client itself, but does not appear when I open the Steam Store within the client and try to use the search box on the site.

Pressure v1.0.2
Windows 7 x64 SP1
Latest Steam Client as of I'm writing this.

**Comment by bykidi** [comment]
Screenshots?
You should opt-in to steam beta client and install fonts included in skin folder.

**Comment by szakigeri** [comment]
Screenshot doesn't show anything. You can see the word 'ffi' typed in, where the cursor is between the second 'f' and the 'i'.

Opting to beta did not help. Fonts were installed from the beginning.

Note: Just moved to Windows 10, format, then clean install, everything reinstalled, the issue is certainly the skin's issue. Other skins don't have it.

**Comment by Js41637** [comment]
Yeah this is a weird bug, It happens to me and does not happen in the normal client, not sure what's going on.

**Comment by bykidi** [comment]
i can confirm that

**Comment by Wiggin38** [comment]
Can also confirm. Happens when I type difficult. Spent the better part of an hour blaming Win10.

**Comment by J5lx** [comment]
For me the bug doesn’t occur - maybe because I’m using Linux? The only mentioned OS in this thread is Windose. Are there any OS X or Linux users experiencing this bug?

**Comment by DirtDiglett** [comment]
I can't reproduce this at all, anything with ffi in it doesn't make the issue appear. Tried in overlay, out of overlay, in every textbox I can find... odd.

**Comment by Wiggin38** [comment]
Very odd. I can confirm it sill happens on my end. Anything we can do to help figure it out ?

**Comment by bykidi** [comment]
@Wiggin38 what is your system language?

**Comment by Zerathos** [comment]
I can reproduce the issue, my system language is English (US).

**Comment by szakigeri** [comment]
My system language is English (US) but my keyboard layout is set to Hungarian.

**Comment by bykidi** [comment]
Pixelvision skin
![default](https://cloud.githubusercontent.com/assets/1337953/9365354/c3a9b7c6-46b9-11e5-80f4-a3df536edddc.PNG)

Vanilla steam
![default](https://cloud.githubusercontent.com/assets/1337953/9365378/e1c4bdf0-46b9-11e5-8a0e-d0bdb5c71159.PNG)

Pressure
![default](https://cloud.githubusercontent.com/assets/1337953/9365418/1d96f442-46ba-11e5-9017-1a1ae9a4f9c3.PNG)

**Comment by Wiggin38** [comment]
@bykidi English (US) Windows 10 Pro. Both Vanilla and Pixelvision work just fine.

**Comment by bykidi** [comment]
I fix that problem by uninstalling NotoSans-Bold.ttf from my X:\Windows\Fonts folder

**Comment by bykidi** [comment]
Can someone confirm that solution?

**Comment by Wiggin38** [comment]
That seems to have "fixed" it. However now a bunch of text is messed up.

**Comment by bykidi** [comment]
@Wiggin38 every NotoSans fonts appears like one in my OS, so yes. if i have any of it installed im getting this bug.

**Comment by bykidi** [comment]
Can you guys test NotoSans font on any other skin? (PixelVision or etc)

**Comment by Wiggin38** [comment]
I did some messing around and "I think" that the issue does NOT happen while using PixelVision and NotoSans.

**Comment by Zerathos** [comment]
Just tried it in Metro for Steam after switching to Noto Sans and was able to get it to happen.

**Comment by DirtDiglett** [comment]
That's really really strange. Can you guys test it out for me with Roboto instead of Noto and let me know if that has the same issue? If not, I may move to Roboto.

**Comment by Wiggin38** [comment]
Looks like Robot is working fine. I am wondering how to change the tote font size.

**Comment by TheLonerD** [comment]
![text-bug](https://cloud.githubusercontent.com/assets/6560567/9545282/ae785e6a-4d90-11e5-9c85-8874af2122e3.gif)

**Comment by DirtDiglett** [comment]
This entire issue is just downright strange.

As a temporary workaround for those of you who get the issue you can install Roboto from Google here: https://www.google.com/fonts/download?kit=hY6_qqcqX_JNp8IlbByiXfesZW2xOQ-xsNqO47m55DA
Then edit the file in includes/settings.styles and change "Noto Sans" to "Roboto"


I will change the default font to Roboto in Pressure² and Pressure Classic during development.

**Comment by bykidi** [comment]
Workaround №2: Disable DirectWrite in steam settings

**Comment by DirtDiglett** [comment]
I've sorted this issue out in [Pressure 1.0.5](https://github.com/DirtDiglett/Pressure-for-Steam/releases/tag/1.0.5)
