### ISSUE TITLE
The filter/ group dropdown doesn't work in small mode

### ISSUE THREAD

**Issue by diggles** [DirtDiglett/Pressure-for-Steam#412]
Clicking the dropdown shows the list correctly, selecting an option doesn't have any effect on the list

Steps to reproduce:
1. Click the Steam menu at the top left
2. Select Small Mode
3. Click the Games dropdown
4. Select a category or sort order

**Comment by bykidi** [comment]
I can confirm that

**Comment by DirtDiglett** [comment]
I'll test this when I get home and fix it up if I can reproduce it.

**Comment by diggles** [comment]
I did a bit more testing to confirm @bykidi comment
The filtering is broken in the current steam beta
Here is the report http://steamcommunity.com/groups/SteamClientBeta/discussions/1/527274088404631207/

Will close as not skin related

**Comment by bykidi** [comment]
Steam Client Beta Update September 10 2015
Fixed mini-mode failing to save the active game filter
