### ISSUE TITLE
THE HOURS ARE OVERLAPPING THE GAME NAME.

### ISSUE THREAD

**Issue by Bobthebob123** [DirtDiglett/Pressure-for-Steam#413]
![screenshot_3](https://cloud.githubusercontent.com/assets/14187153/9746708/884b7f8c-5647-11e5-8263-9fd3a03c0445.png)

**Comment by bykidi** [comment]
feels like you dont have fonts properly installed on your system.
what OS you are on?

**Comment by Bobthebob123** [comment]
I'm on windows 10.

**Comment by DirtDiglett** [comment]
Follow the instructions in the Installation Guide for Pressure. You've not installed the fonts included (Bebas and Noto).
