### ISSUE TITLE
"Add phone number" message bug

### ISSUE THREAD

**Issue by id310791** [DirtDiglett/Pressure-for-Steam#417]
Latest beta client and Pressure 1.0.3
![screenshot from 2015-09-16 09 43 46](https://cloud.githubusercontent.com/assets/9195693/9898098/3687c5c2-5c58-11e5-91cc-6c3f229a6005.png)
![screenshot from 2015-09-16 09 42 47](https://cloud.githubusercontent.com/assets/9195693/9898099/369fdaae-5c58-11e5-8b27-f788576b11a5.png)

**Comment by bykidi** [comment]
I can confirm that

**Comment by Js41637** [comment]
https://github.com/DirtDiglett/Pressure-for-Steam/pull/415

**Comment by DirtDiglett** [comment]
Fixed in the latest commits.
