### ISSUE TITLE
Steam client update - check for updates?

### ISSUE THREAD

**Issue by BKPepe** [DirtDiglett/Pressure-for-Steam#420]
Hello,
Where is the opinion to check update(s)? I can't find it.

In readme is this:
" You must also ensure that you are using the current BETA version of Steam, as otherwise this skin will not work correctly. "

Yeah, but where I can find update(s) for steam client?

**Comment by bykidi** [comment]
https://github.com/DirtDiglett/Pressure-for-Steam/pull/153

Go to steam settings - account - beta testing - Steam Beta.

**Comment by BKPepe** [comment]
I dont mean this. I mean where can I check for updates..

**Comment by FlamingFox911** [comment]
Best way to know if there are beta updates is simply looking here. https://steamcommunity.com/groups/SteamClientBeta
