### ISSUE TITLE
The skin for in Library doesn't work properly

### ISSUE THREAD

**Issue by jantjeb3** [DirtDiglett/Pressure-for-Steam#423]
Just reinstalled my pc, and searched for a new skin for steam(old skin pixelvision) got someone recommended me this skin and installed it.
Got to the problem that when in Library the texts are overlapping at the top, and the top part of steam disappears.

Version: 1.0.4
W7 Ultimate x64 Sp1

Store
![2015-09-18_22-33-16](https://cloud.githubusercontent.com/assets/14353087/9970412/4ed8ad9a-5e55-11e5-8f96-9e86e564910d.jpg)

Library
![2015-09-18_22-19-58](https://cloud.githubusercontent.com/assets/14353087/9970344/e1cd20d2-5e54-11e5-8e08-5015e660a72e.png)

**Comment by GOGO98901** [comment]
Are you using steam beta? That may be why?

**Comment by razephalanx** [comment]
Same happening to me. I'm not on the Beta release for Steam, but when I updated the skin earlier today the skin had that error on the Library page.

**Comment by jantjeb3** [comment]
Nope, I haven't put it on beta yet, normally I'm participating in the beta client, but since the reinstall today i haven't done it yet :/

**Comment by Js41637** [comment]
Yeah the current Github version is for the Beta client, DirtDiglett doesn't seem to use the Github releases to properly separate versions. If you want the version that isn't for the beta client, download this slightly older version. https://github.com/DirtDiglett/Pressure-for-Steam/archive/53f646405d3275e5edc56ca98dc426b9e0a32ebf.zip

**Comment by jantjeb3** [comment]
Haha, i just noticed that in beta it is normal, and works perfectly :D
