### ISSUE TITLE
Library UI issue

### ISSUE THREAD

**Issue by Losgy** [DirtDiglett/Pressure-for-Steam#425]
![submit](https://cloud.githubusercontent.com/assets/14890143/10164842/3ec9c396-66ff-11e5-9b30-926888a57ab8.jpg)

The UI element underneath the heading menus dissapears in the Library 'tab'.

**Comment by bykidi** [comment]
use. damn. steam. BETA. ONLY.
#closed. thank you.

**Comment by FlamingFox911** [comment]
See #423...
