### ISSUE TITLE
System Information option is missing

### ISSUE THREAD

**Issue by Psycic101** [DirtDiglett/Pressure-for-Steam#426]
As per the attached image, the default steam skin has the following option: Help >> System Information, which is required when reporting bugs for games. I cannot find this option under any of the menus when using Pressure for Steam
![missing system information option](https://cloud.githubusercontent.com/assets/983667/10165056/6a969c2a-66bd-11e5-90c6-32cd8df34f70.png)

**Comment by Js41637** [comment]
Yes because it isn't there and has been hidden from the skin. You can edit the `steam.menu` file in `resource/menus` and add
```
SystemInfo {
	text="#steam_menu_systeminfo"
	command="SystemInfo"
}
```
somewhere under `Steam [!$OSX] {` for the Windows version.

**Comment by FlamingFox911** [comment]
Is there a specific reason why you decided to hide it? Is it because there are other better ways to know system information or simply for aesthetic purposes?

**Comment by DirtDiglett** [comment]
>Is there a specific reason why you decided to hide it? Is it because there are other better ways to know system information or simply for aesthetic purposes?

Honest answer? No real reason other than it wasn't really a necessary tool at the time, and far more accurate and extensive information is provided by other tools such as Speccy or even just good old dxdiag. I'll probably pop it back under the Steam Support part in the settings at some point.

**Comment by bykidi** [comment]
include "includes/tweaks/menus/basicmenus.styles"
//include "includes/tweaks/menus/alloptions.styles"

is it possible to recreate?

**Comment by Js41637** [comment]
An all options one would likely only just fit on an 1920x1080 res screen, some less used things are hidden because of this because everything is under one menu.

**Comment by DirtDiglett** [comment]
I've sorted this issue out in [Pressure 1.0.5](https://github.com/DirtDiglett/Pressure-for-Steam/releases/tag/1.0.5)
