### ISSUE TITLE
Software page

### ISSUE THREAD

**Issue by GOGO98901** [DirtDiglett/Pressure-for-Steam#430]
Although you can know what is says the last letters are cut off. I have tried to resize the window to see if it makes a difference but to no luck
![image](https://cloud.githubusercontent.com/assets/2751799/10559178/15b27a0c-74e2-11e5-8146-20240502afbf.png)

**Comment by FlamingFox911** [comment]
Okay. I'm unable to push a request from where I am, however I can assist you to remedy this. Navigate the to the Pressure skin file. Go to resource/layout/ and edit the file called steamrootdialog_gamespage_details.layout. Near the top, find the section labeled emptylisttext. Where it says font-size=15, change the 15 to 14.
