### ISSUE TITLE
Wierd thing in Music settings

### ISSUE THREAD

**Issue by bykidi** [DirtDiglett/Pressure-for-Steam#433]
![default](https://cloud.githubusercontent.com/assets/1337953/10615019/14007f66-7766-11e5-8f19-85834a00ac60.PNG)
Can someone also confirm this?

**Comment by FlamingFox911** [comment]
I do not see this... mind you I am using the beta client with my patch-1.
However, I do see the font clipping in the player. I'll edit this post once I figure out how to fix it.
