### ISSUE TITLE
Downloads "tab" in Settings is showing garbled text

### ISSUE THREAD

**Issue by notnsane** [DirtDiglett/Pressure-for-Steam#434]
I honestly don't know if only I have this issue since it should be reported + fixed already, but here it is:

![image](https://cloud.githubusercontent.com/assets/7162375/10750947/2e62a1ba-7c5a-11e5-8806-c85c82b1443b.png)

Using synced master branch in Steam stable, Windows 10.

**Comment by bykidi** [comment]
https://github.com/DirtDiglett/Pressure-for-Steam/pull/429

**Comment by DirtDiglett** [comment]
This will be fixed in 1.0.6, which I should have out shortly.
