### ISSUE TITLE
Wishlist links dropdown doesn't fully open

### ISSUE THREAD

**Issue by largomaason** [DirtDiglett/Pressure-for-Steam#437]
Went to my wishlist, clicked on the links button and the dropdown does not fully open.  A little sliver opens up and you can click on it and it will take you to the game's community page.
![dropdown](https://cloud.githubusercontent.com/assets/16049433/11445585/09a3d2e8-94f3-11e5-974c-d8f2b595df9a.png)

**Comment by GOGO98901** [comment]
This is not to do with Pressure. It is the same if you go to your wishlist through your browser
