### ISSUE TITLE
Chat tab DnD popup is partly unstyled

### ISSUE THREAD

**Issue by J5lx** [DirtDiglett/Pressure-for-Steam#438]
With the latest Steam beta and Pressure fully updated (no matter whether Steam-Client-Beta or master), the popup that appears when dragging chat tabs is partly unstyled (i.e. looks like the default skin):
![screenshot from 2015-12-28 19-07-532](https://cloud.githubusercontent.com/assets/2063777/12023354/ef1a0898-ad98-11e5-97ae-89066c285229.png)
In case it matters, I have confirmed the issue on both Arch Linux and Windows 7.

**Comment by FlamingFox911** [comment]
This is an issue that also occurs with Default Skin. After poking with Developer mode and the layout files, I can't see any possible way to fix this. You can however bring this up here: http://steamcommunity.com/groups/SteamClientBeta/discussions/0/

**Comment by DirtDiglett** [comment]
Sorry for the delay in response, I've been focusing my attention elsewhere and have been a bit lax in monitoring the Pressure project.

This wasn't originally able to be themed, but Valve added the correct layout file a short time ago so this is something I have in the pipes for 1.0.6
