### ISSUE TITLE
Chat Window Minimizing When Clicking Emoticons

### ISSUE THREAD

**Issue by weirdowatermelon** [DirtDiglett/Pressure-for-Steam#439]
The chat window minimizes when I click every second emoticon from the emoticon menu. I have to manually bring up the chat window again after it happens. Not sure when I started noticing this, probably a few weeks ago. Is this an issue with the skin or with Steam itself? 

I attached a gif of the issue in action: http://i.imgur.com/CvB4KVs.gif

**Comment by FlamingFox911** [comment]
Best way to test is to go to Options --> Interface --> <default skin>.
Also, side note to everyone, as of right now, do NOT download latest update to Steam. You can't launch it for the time being.

**Comment by bykidi** [comment]
I can confirm that.

What is wrong with latest update? Is latest beta broken or what?

**Comment by DirtDiglett** [comment]
This isn't specific to Pressure, I can reproduce this reliably on the default Steam skin on the Beta. Closing.

**Comment by FlamingFox911** [comment]
@bykidi Just saying that at the time of posting the previous post, a beta update made it impossible for anyone to start up Steam, which is why I couldn't check if thus was valid or not. Sorry for the startle.
