### ISSUE TITLE
PLZ add Steam Update funktion

### ISSUE THREAD

**Issue by akks1981** [DirtDiglett/Pressure-for-Steam#440]
Hi i like ure skin very much,

PLZ add the Steam Update to the main menü?

BIG Thx and keep ure nice work on! 

greetings

(sry for my bad English)

**Comment by FlamingFox911** [comment]
Hi @akks1981.
I'd like to point out that an option to check for updates is non-existant on Steam. Steam automatically checks for updates every startup and passively in the background at certain time intervals. If you want to force check for an update, you can use "Restart Steam". Not the best option but it works.

**Comment by DirtDiglett** [comment]
This has been queried before, and there's just no valid reason to add this option. As FlamingFox911 has mentioned, it already does so on its own, there's no need to be force checking for an update yourself - and the added issue of updates often breaking skins/themes means it's self harming to add it.
