### ISSUE TITLE
Menu freezes when clicking "Update news"

### ISSUE THREAD

**Issue by fatek** [DirtDiglett/Pressure-for-Steam#441]
This image shows what happens after clicking "Update news" and then hovering the mouse over STORE and LIBRARY. The rest of the interface behaves normally and I can get rid of the frozen menu by clicking the main menu button again. I am using the Linux version of steam on Linux Mint 17.2.

![pressure frozen menu](https://cloud.githubusercontent.com/assets/12451793/12939694/2779165c-cf77-11e5-9d91-3b708d0cc7a1.png)

**Comment by morevo** [comment]
Maybe it's not a skin bug because on Win when "Notify me about additions[...]" is enabled (Settings/Interface) it will open "Steam - Update News" window, when disabled nothing happend.

**Comment by FlamingFox911** [comment]
I was going to suggest testing with the default interface to see if you get the same result. Chances are, as mentioned above, that it is a Client bug rather than a Skin bug. Please let us know. I don't use Linux ;~;

**Comment by fatek** [comment]
I see now. The menu freezes regardless of skin if you click on "Update news" when the setting "Notify me about additions..." is disabled. I'll close this issue and wait for Valve to fix the client.
