### ISSUE TITLE
Misaligned checkbox in game properties

### ISSUE THREAD

**Issue by Sporty311** [DirtDiglett/Pressure-for-Steam#442]
1. Picka  game from steam library 
2. Go to its properties
3. First tab, top left corner, there is a checkbox.

**Comment by FlamingFox911** [comment]
This is an issue with the regular steam client as well (see Red circle in Image below).
![untitled](https://cloud.githubusercontent.com/assets/11638944/12951166/01ab6d5e-cfdf-11e5-9411-4330d71de073.png)
Seems that someone on the Steam Beta Development Team forgot to add the option "EnableSCTenFootOverlayCheck", as is the setting variable.

**Comment by FlamingFox911** [comment]
Just a note: They added additional settings in the regular setting menu. I have already made the necessary changes. See #444.
