### ISSUE TITLE
long names aren't accounted for in the friends window

### ISSUE THREAD

**Issue by NikWillOrStuff** [DirtDiglett/Pressure-for-Steam#445]
https://www.youtube.com/watch?v=4N3LzRG6Muo

this isn't an issue with the default steam skin because it puts a "..." where the name would go off-screen, then fits the arrow to the left of the scroll bar. that would work here, but with the transparent scroll bar it would leave strange looking dead-space. I'm not sure how you'd fix this without a lot of work.

speaking of a lot of work, I was going to post another issue about the lack of scaling the scroll bar and the friends/groups buttons at the top of the friends window, but you said in another issue that those are very hacky, so I understand why they're not.

these issues alone are what caused one of my friends to decide not to use this skin, after my recommendation.

**Comment by KIPdeKIP** [comment]
As a workaround, right-click on a person.

**Comment by NikWillOrStuff** [comment]
oh jeez, with pressure2 out now, I dunno if he'll ever get around to this. I really don't like pressure2 :P

**Comment by DirtDiglett** [comment]
It's caused by a workaround that was required to prevent the section headings from cutting off before the scrollbar. There is no way to have the scrollbar as it is, and have the headings go full width, and not have the names overflow.

Right click on people's names that it happens on.
