### ISSUE TITLE
Login screen

### ISSUE THREAD

**Issue by Psycic101** [DirtDiglett/Pressure-for-Steam#446]
Any chance you could reskin the login dialogue? The colours look great but most of the text doesn't fit correctly. See image below. This is a very low priority issue, but I thought I'd report it seeing as all the other issues are closed.

![steam-login](https://cloud.githubusercontent.com/assets/983667/13480083/08308342-e0e4-11e5-9695-1d7990aa06db.png)

**Comment by DirtDiglett** [comment]
Please re-read the installation instructions and install the fonts correctly.

**Comment by Psycic101** [comment]
Ok, I'm on Arch Linux and I definitely installed the fonts correctly. As per the Arch wiki, the local fonts folder has changed from ~/.fonts to ~/.local/share/fonts ([see the wiki page](https://wiki.archlinux.org/index.php/fonts#Manual_installation)). So I created a symlink from the new fonts directory to the deprecated ~/.fonts directory and now it is loading the fonts correctly. Perhaps you want to mention this issue on your readme? Regards.
