### ISSUE TITLE
Taskbar preferences setup dialog buggy with new Steam VR checkbox

### ISSUE THREAD

**Issue by bykidi** [DirtDiglett/Pressure-for-Steam#447]
![default](https://cloud.githubusercontent.com/assets/1337953/13745044/e131499e-e9fc-11e5-8c45-d6cd11852a89.PNG)
![2](https://cloud.githubusercontent.com/assets/1337953/13745045/e161e52c-e9fc-11e5-8958-2d51e20dee11.PNG)

**Comment by FlamingFox911** [comment]
Done. See #444.
