### ISSUE TITLE
[Settings] [In-Game tab] "Use Big Picture Overlay when using a Steam Controller from the desktop" checkbox is missing (buggy)

### ISSUE THREAD

**Issue by bykidi** [DirtDiglett/Pressure-for-Steam#448]
![default](https://cloud.githubusercontent.com/assets/1337953/13745109/45b9f780-e9fd-11e5-94d6-1926e2249934.PNG)
![2](https://cloud.githubusercontent.com/assets/1337953/13745110/45c257d6-e9fd-11e5-8131-28227190f8ee.PNG)

**Comment by bykidi** [comment]
Also appears in overlay

![default](https://cloud.githubusercontent.com/assets/1337953/13745232/0c6d1920-e9fe-11e5-845e-f228a7312312.PNG)
![2](https://cloud.githubusercontent.com/assets/1337953/13745258/2d3dafa2-e9fe-11e5-93c0-a5ed34d2f073.PNG)

**Comment by FlamingFox911** [comment]
Done. See #444.
