### ISSUE TITLE
[Settings] [Downloads tab] "Display download rates in bits per second" checkbox is missing (buggy)

### ISSUE THREAD

**Issue by bykidi** [DirtDiglett/Pressure-for-Steam#449]
![default](https://cloud.githubusercontent.com/assets/1337953/13745185/ab5de790-e9fd-11e5-8ff8-011b4a8ce43a.PNG)
![2](https://cloud.githubusercontent.com/assets/1337953/13745186/ab6247ae-e9fd-11e5-9c23-e47bcff13070.PNG)

**Comment by FlamingFox911** [comment]
Done. See #444.
