### ISSUE TITLE
[Linux] In-Game Settings items misaligned

### ISSUE THREAD

**Issue by rgiyf** [DirtDiglett/Pressure-for-Steam#450]
Linux Steam Beta Client Mar 16 2016 package versions 1458187800. On Windows everything is fine.
![screenshot from 2016-03-17 15-49-08](https://cloud.githubusercontent.com/assets/9195693/13846809/d8583dea-ec5a-11e5-89bf-cfd31a61274a.png)
![screenshot from 2016-03-17 15-43-38](https://cloud.githubusercontent.com/assets/9195693/13846836/00cca69e-ec5b-11e5-94f7-9eb806aec185.png)

**Comment by bykidi** [comment]
Try beta steam. You don't have new options that vanilla steam skin should have.

**Comment by FlamingFox911** [comment]
My bad, I know what the error is and I will fix it shortly. I'll upload a fix near the end of the day.

**Comment by rgiyf** [comment]
@FlamingFox911 thank you
@bykidi I'm on beta. Look at the beginning above the first screenshot :)

**Comment by FlamingFox911** [comment]
I think I have fixed the error, but have no way of testings... If you can, go to Steam\skins\Pressure-for-Steam\resource\layout\subpaneloptionsingame.layout, then replace the entire contents with this code. Please message back if it doesn't work. You will have to restart steam for the skin to be updated. `"resource/layout/subpaneloptionsingame.layout" {
	styles {
		Page {
			render_bg {
				0="fill(x0+18,y0+305,x1-43,y0+306, black65)"
				1="fill(x0+18,y0+306,x1-43,y0+307, grey50)"
			}
		}
	}

	layout {
		place {
			controls=DescriptionLabel
			x=18
			y=21
			width=max
			margin-right=43
			dir=down
			spacing=8
		}

		place {
			controls=EnableOverlayCheck
			start=DescriptionLabel
			y=16
			width=max
			dir=down
		}
		
		place [!$OSX&&!$LINUX] {
			controls=EnableSCTenfootOverlayCheck
			region=top
			start=EnableOverlayCheck
			dir=down
			height=20
		}

		place [!$OSX&&!$LINUX] {
			controls=HotKeySelectorLabel
			start=EnableSCTenfootOverlayCheck
			y=10
			dir=down
		}
		
		place [$OSX||$LINUX] {
			controls=HotKeySelectorLabel
			start=EnableOverlayCheck
			y=10
			dir=down
		}

		place {
			controls=HotKeySelector
			start=HotKeySelectorLabel
			y=4
			width=200
			height=24
			dir=down
		}

		place {
			control="Divider1"
			start=HotKeySelector
			y=16
			width=max
			margin-right=43
			dir=down
		}
		place {
			controls=ScreenshotActionLabel
			start=Divider1
			x=240
			y=16
			dir=down
		}

		place {
			controls=ScreenshotNotifyCheck,ScreenshotPlaySoundCheck,ScreenshotSaveUncompressedCheck
			start=ScreenshotActionLabel
			dir=down
			spacing=-6
		}
		place {
			controls=ScreenshotLabel
			start=Divider1
			y=16
			dir=down
		}

		place {
			controls=ScreenshotHotKeySelector
			start=ScreenshotLabel
			y=4
			width=200
			height=24
			dir=down
		}

		place {
			controls=SetScreenshotFolderButton
			start=ScreenshotHotKeySelector
			y=16
			width=200
			height=28
			dir=down
		}
		place {
			controls="PingRateLabel"
			start=SetScreenshotFolderButton
			y=30
			width=max
			dir=down
		}

		place {
			controls="PingRateCombo"
			start=PingRateLabel
			y=4
			width=200
			height=28
			dir=down
		}

		place {
			controls="PingRateInfo"
			start="PingRateCombo"
			y=8
			width=max
			margin-right=43
			dir=down
		}

		place {
			controls="ShowIngameFPSLabel"
			start="PingRateInfo"
			y=16
			width=max
			dir=down
		}

		place {
			controls="ShowInGameFPSCombo"
			start="ShowIngameFPSLabel"
			y=8
			width=200
			height=28
			dir=down
		}

		place {
			controls="ShowIngameFPSContrastCheck"
			start=ShowIngameFPSCombo
			x=16
			width=max
			dir=right
		}


		place {
			control="TitleLabel"
			width=0
			height=0
		}
	}
}`

**Comment by FlamingFox911** [comment]
Hi @rgiyf,
I think I have the solution but I can't test it on Linux or OSX.
Here is my current solution: http://pastebin.com/G9NU8uap
Please let me know if it worked or nah.

**Comment by rgiyf** [comment]
@FlamingFox911 Yeah, it worked but maybe if possible add a little bit more gap where is "In Game Server Browser"(look at screenshot). Also checked it on Windows just in case. Everything fine. And I'm also don't have OSX.
![screenshot from 2016-03-17 22-28-02](https://cloud.githubusercontent.com/assets/9195693/13858732/f2e67966-ec90-11e5-8a37-885af138ae05.png)

**Comment by FlamingFox911** [comment]
Okay, made an adjustment... see if it works.
Same code again, same instruction.

**Comment by rgiyf** [comment]
Something with text 
![screenshot from 2016-03-17 23-20-38](https://cloud.githubusercontent.com/assets/9195693/13859916/e8e08406-ec96-11e5-8264-b1908456180d.png)

**Comment by FlamingFox911** [comment]
Test again, please.

**Comment by rgiyf** [comment]
Same :(

**Comment by FlamingFox911** [comment]
Ok. My brain it completely fried. I don't know how to move/adjust the second divider. It has no control entity. I shuffled back the pastebin to the original fix for the moment, so use that (despite its ugliness). I need time to figure this out, unless someone can tell me how to move the second divider.

Sorry ;~;

**Comment by rgiyf** [comment]
@FlamingFox911 no probs. Everything is fine. Listen... it was a blind guess and a few tries but try line 112 set to y=48, seems it helped :)
![screenshot from 2016-03-18 00-43-21](https://cloud.githubusercontent.com/assets/9195693/13862184/a541d0cc-eca2-11e5-8ee8-88c1721a401c.png)

**Comment by FlamingFox911** [comment]
That was my original solution (and I should have gone with that), but it is not the best. See how there is alot of space between the 2nd divider and the Screenshot options?
I've changed the code in the pastebin again. Try and use that. It should appear the same.

**Comment by rgiyf** [comment]
@FlamingFox911 sorry, I will try tomorrow 😶

**Comment by rgiyf** [comment]
@FlamingFox911 that is from pastebin
![screenshot from 2016-03-18 09-33-29](https://cloud.githubusercontent.com/assets/9195693/13870222/660c161a-eced-11e5-8e4b-f6ae751c60e7.png)

**Comment by FlamingFox911** [comment]
Ok. Good. It works. Not the best solution, but it will have to do for the moment. I'll make a pull request as soon as I can.

**Comment by bykidi** [comment]
Do you have fonts properly installed or it's linux-specific problem?

OK Cancel texts in buttons are lower than expected

High contrast color checkbox text cuts off, see that "g"

**Comment by rgiyf** [comment]
@bykidi it's a linux "specific". Unfortunately it's how this theme fonts are rendering.

**Comment by FlamingFox911** [comment]
Alrighty. I have created the pull request (#452).

**Comment by rgiyf** [comment]
@FlamingFox911 yay😃 thanks
