### ISSUE TITLE
[OSX][Linux] Tester Needed for Patch

### ISSUE THREAD

**Issue by FlamingFox911** [DirtDiglett/Pressure-for-Steam#453]
Hey, Everyone.

I need an OSX and/or Linux tester for the upcoming Pull Request.

There was a recent update that added a few options to the In-Game general settings. I do not have access to these OSes so I cannot verify if what I do will conflict on those OSes. If you can, please copy this code (http://pastebin.com/G9NU8uap) into: `Steam\skins\Pressure-for-Steam\resource\layout\subpaneloptionsingame.layout`

Post any concerns you see here. Screenshots would be nice.

Thanks and cheers.

P.S. I finally know how to move that second divider, so formatting will be much easier now.

**Comment by rgiyf** [comment]
On Ubuntu:
![screenshot from 2016-03-27 20-45-42](https://cloud.githubusercontent.com/assets/9195693/14066814/2b8a0174-f45d-11e5-974a-cde6e284d553.png)

**Comment by bykidi** [comment]
"In-<g>ame FPS counter" that "g" cuts off a little bit

**Comment by FlamingFox911** [comment]
I updated the pastebin so that the bar should be in the proper position. However, I do not see the issue you are getting with the cut off g's. From what I can see it is the same problem with the y's, the p's and any other letter that drops below the line (like q, perhaps). This might be an Linux issue and is out of my hand.

See here:
![untitled](https://cloud.githubusercontent.com/assets/11638944/14067464/2a3ab392-f433-11e5-98a5-0c95bd27b225.png)

**Comment by rgiyf** [comment]
Nice:
![screenshot from 2016-03-27 22-49-53](https://cloud.githubusercontent.com/assets/9195693/14067492/637a58c0-f46e-11e5-9d4b-76b49f2427d7.png)
About fonts. Yes it's linux specific and its font rendering. Not an issue.

**Comment by FlamingFox911** [comment]
Alright thanks for the testing ^-^
