### ISSUE TITLE
[Windows] Settings->In-game new option in beta

### ISSUE THREAD

**Issue by rgiyf** [DirtDiglett/Pressure-for-Steam#454]
New option added to In-game tab in Steam beta.
Option name is "Use Desktop Game Theatre....."
![screenshot 2016-03-27 21 08 21](https://cloud.githubusercontent.com/assets/9195693/14066955/2ea14044-f461-11e5-9f22-84a92ed7a39e.png)
![screenshot 2016-03-27 21 07 49](https://cloud.githubusercontent.com/assets/9195693/14066956/2f144f26-f461-11e5-991a-1c823cf7a323.png)

**Comment by FlamingFox911** [comment]
Taken care of in #452.

**Comment by rgiyf** [comment]
@FlamingFox911 didn't notice :/ closed
