### ISSUE TITLE
Incorrect position checkbox in game properties

### ISSUE THREAD

**Issue by MonkAlex** [DirtDiglett/Pressure-for-Steam#455]
Use russian skin, in game properties new checkbox? :

![image](https://cloud.githubusercontent.com/assets/6784764/14403883/9646dac0-fe79-11e5-8e8f-a53f0c698855.png)

**Comment by FlamingFox911** [comment]
Taken care of in Pull Request #452.

**Comment by m2pt5** [comment]
I'm not getting the updated version when I Download Zip, I still have the misplaced checkbox.

**Comment by Js41637** [comment]
Yeah this is still a pull request so it hasnt been merged, you can download his version from his repo though which is here https://github.com/FlamingFox911/Pressure-for-Steam/tree/Steam-Client-Beta
