### ISSUE TITLE
Added new button to Downloads Settings page

### ISSUE THREAD

**Issue by bykidi** [DirtDiglett/Pressure-for-Steam#458]
11 August - Steam Client Beta Update

Added button to clear local cache under download settings. This may fix downloads by removing stale or corrupt cached data.

![default](https://cloud.githubusercontent.com/assets/1337953/17574971/15bd2c3c-5f6e-11e6-9ae2-54d8d83b0ad8.PNG)

**Comment by FlamingFox911** [comment]
A lot of things were added/changed. I am making another update to my push request shortly.

**Comment by bykidi** [comment]
thanks! 
![default](https://cloud.githubusercontent.com/assets/1337953/17590557/d6f0ee88-5fe2-11e6-9645-890d417bc725.PNG)
