### ISSUE TITLE
Image links broken

### ISSUE THREAD

**Issue by codingHahn** [DirtDiglett/Pressure-for-Steam#459]
I can't open the image links here in Germany. Are they down for you as well?

**Comment by bykidi** [comment]
belarus. got same bug few days ago, not sure if its skin-related or steam's problem.

**Comment by ThalesEu** [comment]
beta update causes this error on steam

**Comment by FlamingFox911** [comment]
Yeah, from the sounds of it, it's a Steam Client error. A quick search has confirmed this: https://steamcommunity.com/groups/SteamClientBeta/discussions/0/360672137538720324/
