### ISSUE TITLE
Beta Update - Move Install Folder.

### ISSUE THREAD

**Issue by FlamingFox911** [DirtDiglett/Pressure-for-Steam#462]
http://pastebin.com/nBTr24Kv

Latest Beta has it so you can move install folder.
The following file (steam/cached/gameproperties_localfiles.res) has been changed to fix that.

Please push.

**Comment by Js41637** [comment]
Oh right I didn't even think that it updated the template, you don't want to submit pull? I'll fix it in about 9 hours.

**Comment by FlamingFox911** [comment]
I don't have rights to push updates to the branch, and I can't be bothered to create another fork for 1 little fix. So, it's all you.

**Comment by Js41637** [comment]
Oh I didn't realize it was just 1 change, you can do it through the website though you know, just click Edit File and GitHub automatically forks and creates a new branch then submits a pull request when you save.
