### ISSUE TITLE
'Updating/downloading the game' window is buggy when the time appears

### ISSUE THREAD

**Issue by bykidi** [DirtDiglett/Pressure-for-Steam#466]
![default](https://cloud.githubusercontent.com/assets/1337953/22625470/002a3e1a-eba9-11e6-8d82-7c8b87ce6345.png)
I'm using latest beta of steam

**Comment by Js41637** [comment]
Oh they added a new box?

**Comment by bykidi** [comment]
I think that everything was the same, no idea why that misalignment happening right now...

**Comment by Js41637** [comment]
I've never seen the Override Current Bandwidth Limit box, I never use that dialog, i'm not sure how long it might have been there.

**Comment by bykidi** [comment]
@Js41637 idk, i always used that window and it was there all the time :D

**Comment by FlamingFox911** [comment]
I've seen this before, but I didn't realize that it kinda overflowed... Spacing fix should resolve this, granted someone can find the associated file.

**Comment by FlamingFox911** [comment]
I think I have squished it enough for it all to fit normally, but I can't really test it 100%. Can you guys locally test [this](http://pastebin.com/7bJJDv2A)? Worse comes to worse, we will have to adjust the graphics/dialogs/gameLaunch image to fit more onto the layout.

**Comment by bykidi** [comment]
Great!

![default](https://cloud.githubusercontent.com/assets/1337953/22629011/74e85dd6-ebef-11e6-9514-4c0e35a4467e.png)

**Comment by bykidi** [comment]
By the way, can you move checkboxes abit to the left?
I mean like that, 2 pixels to the left

![74e85dd6-ebef-11e6-9514-4c0e35a4467e](https://cloud.githubusercontent.com/assets/1337953/22635824/9aad86a6-ec47-11e6-9c5c-05ff7115e2fc.png)

**Comment by Js41637** [comment]
lol

**Comment by bykidi** [comment]
fine... i will do this by myself

**Comment by bykidi** [comment]
![1](https://cloud.githubusercontent.com/assets/1337953/22637548/771be8a2-ec53-11e6-8ecb-ff07099b23db.jpg)

**Comment by FlamingFox911** [comment]
It's fine to have OCD, but wtf? XD Also, thanks for the touch up :)

**Comment by bykidi** [comment]
@FlamingFox911 idk :D 
when i see something i can't unsee anymore - i should fix that asap
