### ISSUE TITLE
Properties\Local Files requires an update

### ISSUE THREAD

**Issue by craterface12** [DirtDiglett/Pressure-for-Steam#470]
Check it out: http://imgur.com/gH6FtKI

**Comment by FlamingFox911** [comment]
This is fixed in the Steam-Client-Beta branch. After some research it seems this feature came out for everyone on the [19th of January](http://store.steampowered.com/news/?feed=steam_client). Which means that the Master will have to get pushed with Steam-Client-Beta's commits.

**Comment by Js41637** [comment]
I just put out a new release for the latest changes from the Steam-Client-Beta branch.
