### ISSUE TITLE
Everything is misplaced

### ISSUE THREAD

**Issue by Deity-** [DirtDiglett/Pressure-for-Steam#472]
Everything except for library, community & friend activity is misplaced. 
Same issue on both 1.0.7 and 1.0.8.
![ss 2017-03-15 at 10 04 19](https://cloud.githubusercontent.com/assets/9532641/23966335/0dc07346-09cc-11e7-8bf0-967ebcb2868f.png)
![ss 2017-03-15 at 10 04 29](https://cloud.githubusercontent.com/assets/9532641/23966334/0dbf024a-09cc-11e7-975f-82519a2a5b0e.png)
![ss 2017-03-15 at 10 04 35](https://cloud.githubusercontent.com/assets/9532641/23966337/0dc351c4-09cc-11e7-9744-ebc80f6996dd.png)
![ss 2017-03-15 at 09 56 45](https://cloud.githubusercontent.com/assets/9532641/23966336/0dc2399c-09cc-11e7-8628-7185d305839e.png)
![ss 2017-03-15 at 09 56 55](https://cloud.githubusercontent.com/assets/9532641/23966339/0dc599ac-09cc-11e7-9bbb-029c907c7a92.png)
![ss 2017-03-15 at 10 01 51](https://cloud.githubusercontent.com/assets/9532641/23966338/0dc3bfce-09cc-11e7-919e-3abf3134f9d7.png)
![ss 2017-03-15 at 10 02 14](https://cloud.githubusercontent.com/assets/9532641/23966341/0ddb51ac-09cc-11e7-9813-4e3641e939c5.png)
![ss 2017-03-15 at 10 03 58](https://cloud.githubusercontent.com/assets/9532641/23966342/0dde7a08-09cc-11e7-87d1-01ed701b419d.png)

**Comment by bykidi** [comment]
Wednesday is routine maintenance day. Steam browser has nothing to do with skin.

**Comment by Deity-** [comment]
Whew, good to know, thanks.

**Comment by Deity-** [comment]
It's now Sunday and everything other than store is still broken.

**Comment by bykidi** [comment]
Try beta client. There is newer web browser component in it.

**Comment by Js41637** [comment]
This has nothing to do with the steam skin, this is web content that the skin doesn't control. Clear your steam cache files.
