### ISSUE TITLE
Problem with Advanced Host Options Dialog in Pressure 1.0.8

### ISSUE THREAD

**Issue by Xiphan** [DirtDiglett/Pressure-for-Steam#474]
![advanced-host](https://cloud.githubusercontent.com/assets/4989354/24473599/1c046486-14ca-11e7-8e4a-9e2276206e15.PNG)

This dialog is located under Settings > In-Home Streaming  > Advanced Host Options

**Comment by FlamingFox911** [comment]
egh I see it... I'll see if I can fix it later today...
