### ISSUE TITLE
New checkbox on interface tab

### ISSUE THREAD

**Issue by avsaponchik** [DirtDiglett/Pressure-for-Steam#481]
![default](https://user-images.githubusercontent.com/1337953/38031159-3e269406-32a3-11e8-99f6-1ee7dd7fa86d.png)
![default](https://user-images.githubusercontent.com/1337953/38031219-67b503de-32a3-11e8-81d5-ed48093930bf.png)

**Comment by Js41637** [comment]
Yeah sorry, i've been meaning to fix this, I just haven't gotten around to it yet, I don't even remember how this thing works anymore lol.

**Comment by FlamingFox911** [comment]
Fixed. Needs to be merged. I also took a bit to scratch my head on this one.

**Comment by Js41637** [comment]
Hey thanks. Looks good, I just made a few spacing changes and added a missing label that I think has been missing since the beginning but I don't know if anything changed recently but it looked weird having the "Window Steam Opens" dropdown without any context. Had it always been that way?

**Comment by Js41637** [comment]
What it looks like for me for context 
![image](https://user-images.githubusercontent.com/6258213/38178805-d5c2d622-365d-11e8-8a13-1708cb1590a8.png)

**Comment by FlamingFox911** [comment]
Looks good. @bykidi let us know.

**Comment by avsaponchik** [comment]
![default](https://user-images.githubusercontent.com/1337953/38183920-b8700c68-364c-11e8-98e9-c5ab9eafdc2f.png)

Sweet! LGFM
