### ISSUE TITLE
New Steam Update

### ISSUE THREAD

**Issue by faedy2** [DirtDiglett/Pressure-for-Steam#487]
Hello everyone. Steam got a new update for friends and chat, and it pretty much broke your entire skin.

**Comment by Js41637** [comment]
You can download the Beta branch

https://github.com/DirtDiglett/Pressure-for-Steam/archive/Steam-Client-Beta.zip

**Comment by Owned67** [comment]
Possible to add: busy status?

he was removed with latest update :(

**Comment by Js41637** [comment]
The skin cant style any of the new chat or add features that were removed.

Sorry.

**Comment by faedy2** [comment]
Thanks @Js41637
