### ISSUE TITLE
Main window (mostly about header)

### ISSUE THREAD

**Issue by iwsfg** [DirtDiglett/Pressure-for-Steam#66]
I'm just being picky now, but there's few things that bugs me:
### 1. Address bar

![](http://i.imgur.com/6189Ox5.png)

It's always readonly there, so maybe it does not have to be white? It was literaly hurting my eyes, when inactive items on top of it was all black too, and there was black above it, black below it and white address bar in the middle. Also having some left padding would be nice.

like 
![](http://i.imgur.com/qKlRzoX.png)

small triangle thing under selected menu item is more visible like this too, as for me
### 2. If address bar color is not a subject of change, maybe line up white to white?

![](http://i.imgur.com/paKcRxc.png)

It might be lined up with Search bar placeholder currently though, I'm not sure
### 3. Search bar and sidebar width does not match in games library

Maybe search bar should be little wider 
![](http://i.imgur.com/6ywQHTu.png)
### 4. Sidebar in games/software section is wider than in music section of library

![](http://i.imgur.com/K26MRYu.png)

But probably music section wasn't changed that much yet, it looks a lot like default skin

**Comment by Iwasawafag** [comment]
> I was under the assumption that in the Community tab that URL bar becomes editable... but I just checked and you're correct - it is always disabled.

I just found out, that valve coded it so well, that even if other keyboard shortcuts are disabled for disabled field, Ctrl+Z still works for it and wiping out content of the field.

Just fun fact. Sorry
