### ISSUE TITLE
[Not important] Support for Steam's small mode

### ISSUE THREAD

**Issue by J5lx** [DirtDiglett/Pressure-for-Steam#72]
Currently Pressure looks like this in small mode:

![Steam in small mode with Pressure skin](https://cloud.githubusercontent.com/assets/2063777/4899749/743467a4-641f-11e4-8b1a-a71d07592b09.png)

Also, you have to use a trick to get into the small mode with Pressure:
1. Open Steam with the default theme
2. Switch to small mode
3. Change the skin to Pressure
4. Restart Steam

Therefore this is what I'm looking for:
1. a menu entry for small mode in standard mode
2. styling for small mode

It's not urgent though, so you don't need to do this right now.

**Comment by Asphira** [comment]
I might be adding support for this eventually, but I plan to get downloads and quite a few other things fixed prior, it is very low priority
